// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BF.AgentMaster.proto

package com.benq.csgov2.common.protobuf;

public final class BFAgentMaster {
  private BFAgentMaster() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface VerStructOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BF.AgentMaster.VerStruct)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 iFrameVer = 1;</code>
     */
    boolean hasIFrameVer();
    /**
     * <code>required int32 iFrameVer = 1;</code>
     */
    int getIFrameVer();

    /**
     * <code>required int32 iSubVer = 2;</code>
     */
    boolean hasISubVer();
    /**
     * <code>required int32 iSubVer = 2;</code>
     */
    int getISubVer();

    /**
     * <code>required int32 iUpdateVer = 3;</code>
     */
    boolean hasIUpdateVer();
    /**
     * <code>required int32 iUpdateVer = 3;</code>
     */
    int getIUpdateVer();

    /**
     * <code>required int32 iBuildVer = 4;</code>
     */
    boolean hasIBuildVer();
    /**
     * <code>required int32 iBuildVer = 4;</code>
     */
    int getIBuildVer();

    /**
     * <code>required string AppVer = 5;</code>
     */
    boolean hasAppVer();
    /**
     * <code>required string AppVer = 5;</code>
     */
    java.lang.String getAppVer();
    /**
     * <code>required string AppVer = 5;</code>
     */
    com.google.protobuf.ByteString
        getAppVerBytes();
  }
  /**
   * Protobuf type {@code BF.AgentMaster.VerStruct}
   */
  public static final class VerStruct extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:BF.AgentMaster.VerStruct)
      VerStructOrBuilder {
    // Use VerStruct.newBuilder() to construct.
    private VerStruct(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private VerStruct(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final VerStruct defaultInstance;
    public static VerStruct getDefaultInstance() {
      return defaultInstance;
    }

    public VerStruct getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private VerStruct(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              iFrameVer_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              iSubVer_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              iUpdateVer_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              iBuildVer_ = input.readInt32();
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              appVer_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.benq.csgov2.common.protobuf.BFAgentMaster.internal_static_BF_AgentMaster_VerStruct_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.benq.csgov2.common.protobuf.BFAgentMaster.internal_static_BF_AgentMaster_VerStruct_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.benq.csgov2.common.protobuf.BFAgentMaster.VerStruct.class, com.benq.csgov2.common.protobuf.BFAgentMaster.VerStruct.Builder.class);
    }

    public static com.google.protobuf.Parser<VerStruct> PARSER =
        new com.google.protobuf.AbstractParser<VerStruct>() {
      public VerStruct parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new VerStruct(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<VerStruct> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int IFRAMEVER_FIELD_NUMBER = 1;
    private int iFrameVer_;
    /**
     * <code>required int32 iFrameVer = 1;</code>
     */
    public boolean hasIFrameVer() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 iFrameVer = 1;</code>
     */
    public int getIFrameVer() {
      return iFrameVer_;
    }

    public static final int ISUBVER_FIELD_NUMBER = 2;
    private int iSubVer_;
    /**
     * <code>required int32 iSubVer = 2;</code>
     */
    public boolean hasISubVer() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 iSubVer = 2;</code>
     */
    public int getISubVer() {
      return iSubVer_;
    }

    public static final int IUPDATEVER_FIELD_NUMBER = 3;
    private int iUpdateVer_;
    /**
     * <code>required int32 iUpdateVer = 3;</code>
     */
    public boolean hasIUpdateVer() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 iUpdateVer = 3;</code>
     */
    public int getIUpdateVer() {
      return iUpdateVer_;
    }

    public static final int IBUILDVER_FIELD_NUMBER = 4;
    private int iBuildVer_;
    /**
     * <code>required int32 iBuildVer = 4;</code>
     */
    public boolean hasIBuildVer() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 iBuildVer = 4;</code>
     */
    public int getIBuildVer() {
      return iBuildVer_;
    }

    public static final int APPVER_FIELD_NUMBER = 5;
    private java.lang.Object appVer_;
    /**
     * <code>required string AppVer = 5;</code>
     */
    public boolean hasAppVer() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required string AppVer = 5;</code>
     */
    public java.lang.String getAppVer() {
      java.lang.Object ref = appVer_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          appVer_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string AppVer = 5;</code>
     */
    public com.google.protobuf.ByteString
        getAppVerBytes() {
      java.lang.Object ref = appVer_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appVer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      iFrameVer_ = 0;
      iSubVer_ = 0;
      iUpdateVer_ = 0;
      iBuildVer_ = 0;
      appVer_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasIFrameVer()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasISubVer()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIUpdateVer()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIBuildVer()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAppVer()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, iFrameVer_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, iSubVer_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, iUpdateVer_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, iBuildVer_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getAppVerBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, iFrameVer_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, iSubVer_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, iUpdateVer_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, iBuildVer_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getAppVerBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.benq.csgov2.common.protobuf.BFAgentMaster.VerStruct parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.benq.csgov2.common.protobuf.BFAgentMaster.VerStruct parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.benq.csgov2.common.protobuf.BFAgentMaster.VerStruct parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.benq.csgov2.common.protobuf.BFAgentMaster.VerStruct parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.benq.csgov2.common.protobuf.BFAgentMaster.VerStruct parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.benq.csgov2.common.protobuf.BFAgentMaster.VerStruct parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.benq.csgov2.common.protobuf.BFAgentMaster.VerStruct parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.benq.csgov2.common.protobuf.BFAgentMaster.VerStruct parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.benq.csgov2.common.protobuf.BFAgentMaster.VerStruct parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.benq.csgov2.common.protobuf.BFAgentMaster.VerStruct parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.benq.csgov2.common.protobuf.BFAgentMaster.VerStruct prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BF.AgentMaster.VerStruct}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BF.AgentMaster.VerStruct)
        com.benq.csgov2.common.protobuf.BFAgentMaster.VerStructOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.benq.csgov2.common.protobuf.BFAgentMaster.internal_static_BF_AgentMaster_VerStruct_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.benq.csgov2.common.protobuf.BFAgentMaster.internal_static_BF_AgentMaster_VerStruct_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.benq.csgov2.common.protobuf.BFAgentMaster.VerStruct.class, com.benq.csgov2.common.protobuf.BFAgentMaster.VerStruct.Builder.class);
      }

      // Construct using com.benq.csgov2.common.protobuf.BFAgentMaster.VerStruct.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        iFrameVer_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        iSubVer_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        iUpdateVer_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        iBuildVer_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        appVer_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.benq.csgov2.common.protobuf.BFAgentMaster.internal_static_BF_AgentMaster_VerStruct_descriptor;
      }

      public com.benq.csgov2.common.protobuf.BFAgentMaster.VerStruct getDefaultInstanceForType() {
        return com.benq.csgov2.common.protobuf.BFAgentMaster.VerStruct.getDefaultInstance();
      }

      public com.benq.csgov2.common.protobuf.BFAgentMaster.VerStruct build() {
        com.benq.csgov2.common.protobuf.BFAgentMaster.VerStruct result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.benq.csgov2.common.protobuf.BFAgentMaster.VerStruct buildPartial() {
        com.benq.csgov2.common.protobuf.BFAgentMaster.VerStruct result = new com.benq.csgov2.common.protobuf.BFAgentMaster.VerStruct(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.iFrameVer_ = iFrameVer_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.iSubVer_ = iSubVer_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.iUpdateVer_ = iUpdateVer_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.iBuildVer_ = iBuildVer_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.appVer_ = appVer_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.benq.csgov2.common.protobuf.BFAgentMaster.VerStruct) {
          return mergeFrom((com.benq.csgov2.common.protobuf.BFAgentMaster.VerStruct)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.benq.csgov2.common.protobuf.BFAgentMaster.VerStruct other) {
        if (other == com.benq.csgov2.common.protobuf.BFAgentMaster.VerStruct.getDefaultInstance()) return this;
        if (other.hasIFrameVer()) {
          setIFrameVer(other.getIFrameVer());
        }
        if (other.hasISubVer()) {
          setISubVer(other.getISubVer());
        }
        if (other.hasIUpdateVer()) {
          setIUpdateVer(other.getIUpdateVer());
        }
        if (other.hasIBuildVer()) {
          setIBuildVer(other.getIBuildVer());
        }
        if (other.hasAppVer()) {
          bitField0_ |= 0x00000010;
          appVer_ = other.appVer_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasIFrameVer()) {
          
          return false;
        }
        if (!hasISubVer()) {
          
          return false;
        }
        if (!hasIUpdateVer()) {
          
          return false;
        }
        if (!hasIBuildVer()) {
          
          return false;
        }
        if (!hasAppVer()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.benq.csgov2.common.protobuf.BFAgentMaster.VerStruct parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.benq.csgov2.common.protobuf.BFAgentMaster.VerStruct) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int iFrameVer_ ;
      /**
       * <code>required int32 iFrameVer = 1;</code>
       */
      public boolean hasIFrameVer() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 iFrameVer = 1;</code>
       */
      public int getIFrameVer() {
        return iFrameVer_;
      }
      /**
       * <code>required int32 iFrameVer = 1;</code>
       */
      public Builder setIFrameVer(int value) {
        bitField0_ |= 0x00000001;
        iFrameVer_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 iFrameVer = 1;</code>
       */
      public Builder clearIFrameVer() {
        bitField0_ = (bitField0_ & ~0x00000001);
        iFrameVer_ = 0;
        onChanged();
        return this;
      }

      private int iSubVer_ ;
      /**
       * <code>required int32 iSubVer = 2;</code>
       */
      public boolean hasISubVer() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 iSubVer = 2;</code>
       */
      public int getISubVer() {
        return iSubVer_;
      }
      /**
       * <code>required int32 iSubVer = 2;</code>
       */
      public Builder setISubVer(int value) {
        bitField0_ |= 0x00000002;
        iSubVer_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 iSubVer = 2;</code>
       */
      public Builder clearISubVer() {
        bitField0_ = (bitField0_ & ~0x00000002);
        iSubVer_ = 0;
        onChanged();
        return this;
      }

      private int iUpdateVer_ ;
      /**
       * <code>required int32 iUpdateVer = 3;</code>
       */
      public boolean hasIUpdateVer() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 iUpdateVer = 3;</code>
       */
      public int getIUpdateVer() {
        return iUpdateVer_;
      }
      /**
       * <code>required int32 iUpdateVer = 3;</code>
       */
      public Builder setIUpdateVer(int value) {
        bitField0_ |= 0x00000004;
        iUpdateVer_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 iUpdateVer = 3;</code>
       */
      public Builder clearIUpdateVer() {
        bitField0_ = (bitField0_ & ~0x00000004);
        iUpdateVer_ = 0;
        onChanged();
        return this;
      }

      private int iBuildVer_ ;
      /**
       * <code>required int32 iBuildVer = 4;</code>
       */
      public boolean hasIBuildVer() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 iBuildVer = 4;</code>
       */
      public int getIBuildVer() {
        return iBuildVer_;
      }
      /**
       * <code>required int32 iBuildVer = 4;</code>
       */
      public Builder setIBuildVer(int value) {
        bitField0_ |= 0x00000008;
        iBuildVer_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 iBuildVer = 4;</code>
       */
      public Builder clearIBuildVer() {
        bitField0_ = (bitField0_ & ~0x00000008);
        iBuildVer_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object appVer_ = "";
      /**
       * <code>required string AppVer = 5;</code>
       */
      public boolean hasAppVer() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required string AppVer = 5;</code>
       */
      public java.lang.String getAppVer() {
        java.lang.Object ref = appVer_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            appVer_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string AppVer = 5;</code>
       */
      public com.google.protobuf.ByteString
          getAppVerBytes() {
        java.lang.Object ref = appVer_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          appVer_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string AppVer = 5;</code>
       */
      public Builder setAppVer(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        appVer_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string AppVer = 5;</code>
       */
      public Builder clearAppVer() {
        bitField0_ = (bitField0_ & ~0x00000010);
        appVer_ = getDefaultInstance().getAppVer();
        onChanged();
        return this;
      }
      /**
       * <code>required string AppVer = 5;</code>
       */
      public Builder setAppVerBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        appVer_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:BF.AgentMaster.VerStruct)
    }

    static {
      defaultInstance = new VerStruct(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:BF.AgentMaster.VerStruct)
  }

  public interface AgentAskWorkReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BF.AgentMaster.AgentAskWorkReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .BF.AgentMaster.VerStruct AppVerStruct = 1;</code>
     *
     * <pre>
     *AGENT_ASK_FOR_WORK_ADDRESS_REQ
     * </pre>
     */
    boolean hasAppVerStruct();
    /**
     * <code>required .BF.AgentMaster.VerStruct AppVerStruct = 1;</code>
     *
     * <pre>
     *AGENT_ASK_FOR_WORK_ADDRESS_REQ
     * </pre>
     */
    com.benq.csgov2.common.protobuf.BFAgentMaster.VerStruct getAppVerStruct();
    /**
     * <code>required .BF.AgentMaster.VerStruct AppVerStruct = 1;</code>
     *
     * <pre>
     *AGENT_ASK_FOR_WORK_ADDRESS_REQ
     * </pre>
     */
    com.benq.csgov2.common.protobuf.BFAgentMaster.VerStructOrBuilder getAppVerStructOrBuilder();

    /**
     * <code>required string reserve = 2;</code>
     *
     * <pre>
     *保留字段，当下固定为”cs2go2015”
     * </pre>
     */
    boolean hasReserve();
    /**
     * <code>required string reserve = 2;</code>
     *
     * <pre>
     *保留字段，当下固定为”cs2go2015”
     * </pre>
     */
    java.lang.String getReserve();
    /**
     * <code>required string reserve = 2;</code>
     *
     * <pre>
     *保留字段，当下固定为”cs2go2015”
     * </pre>
     */
    com.google.protobuf.ByteString
        getReserveBytes();
  }
  /**
   * Protobuf type {@code BF.AgentMaster.AgentAskWorkReq}
   */
  public static final class AgentAskWorkReq extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:BF.AgentMaster.AgentAskWorkReq)
      AgentAskWorkReqOrBuilder {
    // Use AgentAskWorkReq.newBuilder() to construct.
    private AgentAskWorkReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AgentAskWorkReq(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AgentAskWorkReq defaultInstance;
    public static AgentAskWorkReq getDefaultInstance() {
      return defaultInstance;
    }

    public AgentAskWorkReq getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AgentAskWorkReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.benq.csgov2.common.protobuf.BFAgentMaster.VerStruct.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = appVerStruct_.toBuilder();
              }
              appVerStruct_ = input.readMessage(com.benq.csgov2.common.protobuf.BFAgentMaster.VerStruct.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(appVerStruct_);
                appVerStruct_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              reserve_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.benq.csgov2.common.protobuf.BFAgentMaster.internal_static_BF_AgentMaster_AgentAskWorkReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.benq.csgov2.common.protobuf.BFAgentMaster.internal_static_BF_AgentMaster_AgentAskWorkReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.benq.csgov2.common.protobuf.BFAgentMaster.AgentAskWorkReq.class, com.benq.csgov2.common.protobuf.BFAgentMaster.AgentAskWorkReq.Builder.class);
    }

    public static com.google.protobuf.Parser<AgentAskWorkReq> PARSER =
        new com.google.protobuf.AbstractParser<AgentAskWorkReq>() {
      public AgentAskWorkReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AgentAskWorkReq(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AgentAskWorkReq> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int APPVERSTRUCT_FIELD_NUMBER = 1;
    private com.benq.csgov2.common.protobuf.BFAgentMaster.VerStruct appVerStruct_;
    /**
     * <code>required .BF.AgentMaster.VerStruct AppVerStruct = 1;</code>
     *
     * <pre>
     *AGENT_ASK_FOR_WORK_ADDRESS_REQ
     * </pre>
     */
    public boolean hasAppVerStruct() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .BF.AgentMaster.VerStruct AppVerStruct = 1;</code>
     *
     * <pre>
     *AGENT_ASK_FOR_WORK_ADDRESS_REQ
     * </pre>
     */
    public com.benq.csgov2.common.protobuf.BFAgentMaster.VerStruct getAppVerStruct() {
      return appVerStruct_;
    }
    /**
     * <code>required .BF.AgentMaster.VerStruct AppVerStruct = 1;</code>
     *
     * <pre>
     *AGENT_ASK_FOR_WORK_ADDRESS_REQ
     * </pre>
     */
    public com.benq.csgov2.common.protobuf.BFAgentMaster.VerStructOrBuilder getAppVerStructOrBuilder() {
      return appVerStruct_;
    }

    public static final int RESERVE_FIELD_NUMBER = 2;
    private java.lang.Object reserve_;
    /**
     * <code>required string reserve = 2;</code>
     *
     * <pre>
     *保留字段，当下固定为”cs2go2015”
     * </pre>
     */
    public boolean hasReserve() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string reserve = 2;</code>
     *
     * <pre>
     *保留字段，当下固定为”cs2go2015”
     * </pre>
     */
    public java.lang.String getReserve() {
      java.lang.Object ref = reserve_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          reserve_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string reserve = 2;</code>
     *
     * <pre>
     *保留字段，当下固定为”cs2go2015”
     * </pre>
     */
    public com.google.protobuf.ByteString
        getReserveBytes() {
      java.lang.Object ref = reserve_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reserve_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      appVerStruct_ = com.benq.csgov2.common.protobuf.BFAgentMaster.VerStruct.getDefaultInstance();
      reserve_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasAppVerStruct()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasReserve()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getAppVerStruct().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, appVerStruct_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getReserveBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, appVerStruct_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getReserveBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.benq.csgov2.common.protobuf.BFAgentMaster.AgentAskWorkReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.benq.csgov2.common.protobuf.BFAgentMaster.AgentAskWorkReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.benq.csgov2.common.protobuf.BFAgentMaster.AgentAskWorkReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.benq.csgov2.common.protobuf.BFAgentMaster.AgentAskWorkReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.benq.csgov2.common.protobuf.BFAgentMaster.AgentAskWorkReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.benq.csgov2.common.protobuf.BFAgentMaster.AgentAskWorkReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.benq.csgov2.common.protobuf.BFAgentMaster.AgentAskWorkReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.benq.csgov2.common.protobuf.BFAgentMaster.AgentAskWorkReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.benq.csgov2.common.protobuf.BFAgentMaster.AgentAskWorkReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.benq.csgov2.common.protobuf.BFAgentMaster.AgentAskWorkReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.benq.csgov2.common.protobuf.BFAgentMaster.AgentAskWorkReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BF.AgentMaster.AgentAskWorkReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BF.AgentMaster.AgentAskWorkReq)
        com.benq.csgov2.common.protobuf.BFAgentMaster.AgentAskWorkReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.benq.csgov2.common.protobuf.BFAgentMaster.internal_static_BF_AgentMaster_AgentAskWorkReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.benq.csgov2.common.protobuf.BFAgentMaster.internal_static_BF_AgentMaster_AgentAskWorkReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.benq.csgov2.common.protobuf.BFAgentMaster.AgentAskWorkReq.class, com.benq.csgov2.common.protobuf.BFAgentMaster.AgentAskWorkReq.Builder.class);
      }

      // Construct using com.benq.csgov2.common.protobuf.BFAgentMaster.AgentAskWorkReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getAppVerStructFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (appVerStructBuilder_ == null) {
          appVerStruct_ = com.benq.csgov2.common.protobuf.BFAgentMaster.VerStruct.getDefaultInstance();
        } else {
          appVerStructBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        reserve_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.benq.csgov2.common.protobuf.BFAgentMaster.internal_static_BF_AgentMaster_AgentAskWorkReq_descriptor;
      }

      public com.benq.csgov2.common.protobuf.BFAgentMaster.AgentAskWorkReq getDefaultInstanceForType() {
        return com.benq.csgov2.common.protobuf.BFAgentMaster.AgentAskWorkReq.getDefaultInstance();
      }

      public com.benq.csgov2.common.protobuf.BFAgentMaster.AgentAskWorkReq build() {
        com.benq.csgov2.common.protobuf.BFAgentMaster.AgentAskWorkReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.benq.csgov2.common.protobuf.BFAgentMaster.AgentAskWorkReq buildPartial() {
        com.benq.csgov2.common.protobuf.BFAgentMaster.AgentAskWorkReq result = new com.benq.csgov2.common.protobuf.BFAgentMaster.AgentAskWorkReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (appVerStructBuilder_ == null) {
          result.appVerStruct_ = appVerStruct_;
        } else {
          result.appVerStruct_ = appVerStructBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.reserve_ = reserve_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.benq.csgov2.common.protobuf.BFAgentMaster.AgentAskWorkReq) {
          return mergeFrom((com.benq.csgov2.common.protobuf.BFAgentMaster.AgentAskWorkReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.benq.csgov2.common.protobuf.BFAgentMaster.AgentAskWorkReq other) {
        if (other == com.benq.csgov2.common.protobuf.BFAgentMaster.AgentAskWorkReq.getDefaultInstance()) return this;
        if (other.hasAppVerStruct()) {
          mergeAppVerStruct(other.getAppVerStruct());
        }
        if (other.hasReserve()) {
          bitField0_ |= 0x00000002;
          reserve_ = other.reserve_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasAppVerStruct()) {
          
          return false;
        }
        if (!hasReserve()) {
          
          return false;
        }
        if (!getAppVerStruct().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.benq.csgov2.common.protobuf.BFAgentMaster.AgentAskWorkReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.benq.csgov2.common.protobuf.BFAgentMaster.AgentAskWorkReq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.benq.csgov2.common.protobuf.BFAgentMaster.VerStruct appVerStruct_ = com.benq.csgov2.common.protobuf.BFAgentMaster.VerStruct.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.benq.csgov2.common.protobuf.BFAgentMaster.VerStruct, com.benq.csgov2.common.protobuf.BFAgentMaster.VerStruct.Builder, com.benq.csgov2.common.protobuf.BFAgentMaster.VerStructOrBuilder> appVerStructBuilder_;
      /**
       * <code>required .BF.AgentMaster.VerStruct AppVerStruct = 1;</code>
       *
       * <pre>
       *AGENT_ASK_FOR_WORK_ADDRESS_REQ
       * </pre>
       */
      public boolean hasAppVerStruct() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .BF.AgentMaster.VerStruct AppVerStruct = 1;</code>
       *
       * <pre>
       *AGENT_ASK_FOR_WORK_ADDRESS_REQ
       * </pre>
       */
      public com.benq.csgov2.common.protobuf.BFAgentMaster.VerStruct getAppVerStruct() {
        if (appVerStructBuilder_ == null) {
          return appVerStruct_;
        } else {
          return appVerStructBuilder_.getMessage();
        }
      }
      /**
       * <code>required .BF.AgentMaster.VerStruct AppVerStruct = 1;</code>
       *
       * <pre>
       *AGENT_ASK_FOR_WORK_ADDRESS_REQ
       * </pre>
       */
      public Builder setAppVerStruct(com.benq.csgov2.common.protobuf.BFAgentMaster.VerStruct value) {
        if (appVerStructBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          appVerStruct_ = value;
          onChanged();
        } else {
          appVerStructBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .BF.AgentMaster.VerStruct AppVerStruct = 1;</code>
       *
       * <pre>
       *AGENT_ASK_FOR_WORK_ADDRESS_REQ
       * </pre>
       */
      public Builder setAppVerStruct(
          com.benq.csgov2.common.protobuf.BFAgentMaster.VerStruct.Builder builderForValue) {
        if (appVerStructBuilder_ == null) {
          appVerStruct_ = builderForValue.build();
          onChanged();
        } else {
          appVerStructBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .BF.AgentMaster.VerStruct AppVerStruct = 1;</code>
       *
       * <pre>
       *AGENT_ASK_FOR_WORK_ADDRESS_REQ
       * </pre>
       */
      public Builder mergeAppVerStruct(com.benq.csgov2.common.protobuf.BFAgentMaster.VerStruct value) {
        if (appVerStructBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              appVerStruct_ != com.benq.csgov2.common.protobuf.BFAgentMaster.VerStruct.getDefaultInstance()) {
            appVerStruct_ =
              com.benq.csgov2.common.protobuf.BFAgentMaster.VerStruct.newBuilder(appVerStruct_).mergeFrom(value).buildPartial();
          } else {
            appVerStruct_ = value;
          }
          onChanged();
        } else {
          appVerStructBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .BF.AgentMaster.VerStruct AppVerStruct = 1;</code>
       *
       * <pre>
       *AGENT_ASK_FOR_WORK_ADDRESS_REQ
       * </pre>
       */
      public Builder clearAppVerStruct() {
        if (appVerStructBuilder_ == null) {
          appVerStruct_ = com.benq.csgov2.common.protobuf.BFAgentMaster.VerStruct.getDefaultInstance();
          onChanged();
        } else {
          appVerStructBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .BF.AgentMaster.VerStruct AppVerStruct = 1;</code>
       *
       * <pre>
       *AGENT_ASK_FOR_WORK_ADDRESS_REQ
       * </pre>
       */
      public com.benq.csgov2.common.protobuf.BFAgentMaster.VerStruct.Builder getAppVerStructBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getAppVerStructFieldBuilder().getBuilder();
      }
      /**
       * <code>required .BF.AgentMaster.VerStruct AppVerStruct = 1;</code>
       *
       * <pre>
       *AGENT_ASK_FOR_WORK_ADDRESS_REQ
       * </pre>
       */
      public com.benq.csgov2.common.protobuf.BFAgentMaster.VerStructOrBuilder getAppVerStructOrBuilder() {
        if (appVerStructBuilder_ != null) {
          return appVerStructBuilder_.getMessageOrBuilder();
        } else {
          return appVerStruct_;
        }
      }
      /**
       * <code>required .BF.AgentMaster.VerStruct AppVerStruct = 1;</code>
       *
       * <pre>
       *AGENT_ASK_FOR_WORK_ADDRESS_REQ
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.benq.csgov2.common.protobuf.BFAgentMaster.VerStruct, com.benq.csgov2.common.protobuf.BFAgentMaster.VerStruct.Builder, com.benq.csgov2.common.protobuf.BFAgentMaster.VerStructOrBuilder> 
          getAppVerStructFieldBuilder() {
        if (appVerStructBuilder_ == null) {
          appVerStructBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.benq.csgov2.common.protobuf.BFAgentMaster.VerStruct, com.benq.csgov2.common.protobuf.BFAgentMaster.VerStruct.Builder, com.benq.csgov2.common.protobuf.BFAgentMaster.VerStructOrBuilder>(
                  getAppVerStruct(),
                  getParentForChildren(),
                  isClean());
          appVerStruct_ = null;
        }
        return appVerStructBuilder_;
      }

      private java.lang.Object reserve_ = "";
      /**
       * <code>required string reserve = 2;</code>
       *
       * <pre>
       *保留字段，当下固定为”cs2go2015”
       * </pre>
       */
      public boolean hasReserve() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string reserve = 2;</code>
       *
       * <pre>
       *保留字段，当下固定为”cs2go2015”
       * </pre>
       */
      public java.lang.String getReserve() {
        java.lang.Object ref = reserve_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            reserve_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string reserve = 2;</code>
       *
       * <pre>
       *保留字段，当下固定为”cs2go2015”
       * </pre>
       */
      public com.google.protobuf.ByteString
          getReserveBytes() {
        java.lang.Object ref = reserve_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          reserve_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string reserve = 2;</code>
       *
       * <pre>
       *保留字段，当下固定为”cs2go2015”
       * </pre>
       */
      public Builder setReserve(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        reserve_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string reserve = 2;</code>
       *
       * <pre>
       *保留字段，当下固定为”cs2go2015”
       * </pre>
       */
      public Builder clearReserve() {
        bitField0_ = (bitField0_ & ~0x00000002);
        reserve_ = getDefaultInstance().getReserve();
        onChanged();
        return this;
      }
      /**
       * <code>required string reserve = 2;</code>
       *
       * <pre>
       *保留字段，当下固定为”cs2go2015”
       * </pre>
       */
      public Builder setReserveBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        reserve_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:BF.AgentMaster.AgentAskWorkReq)
    }

    static {
      defaultInstance = new AgentAskWorkReq(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:BF.AgentMaster.AgentAskWorkReq)
  }

  public interface AgentAskWorkRspOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BF.AgentMaster.AgentAskWorkRsp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 state = 1;</code>
     *
     * <pre>
     *AGENT_ASK_FOR_WORK_ADDRESS_RSP
     * </pre>
     */
    boolean hasState();
    /**
     * <code>required int32 state = 1;</code>
     *
     * <pre>
     *AGENT_ASK_FOR_WORK_ADDRESS_RSP
     * </pre>
     */
    int getState();

    /**
     * <code>required string ip = 2;</code>
     *
     * <pre>
     *状态：返回0,表示OK,ip和port字段有效(允许使用)
     *返回1，表示版本太低需要升级，但依然可以使用(允许使用)
     *返回2,表示保留字段(密码错误) (禁止使用)
     *返回3，其他错误(禁止使用)
     * </pre>
     */
    boolean hasIp();
    /**
     * <code>required string ip = 2;</code>
     *
     * <pre>
     *状态：返回0,表示OK,ip和port字段有效(允许使用)
     *返回1，表示版本太低需要升级，但依然可以使用(允许使用)
     *返回2,表示保留字段(密码错误) (禁止使用)
     *返回3，其他错误(禁止使用)
     * </pre>
     */
    java.lang.String getIp();
    /**
     * <code>required string ip = 2;</code>
     *
     * <pre>
     *状态：返回0,表示OK,ip和port字段有效(允许使用)
     *返回1，表示版本太低需要升级，但依然可以使用(允许使用)
     *返回2,表示保留字段(密码错误) (禁止使用)
     *返回3，其他错误(禁止使用)
     * </pre>
     */
    com.google.protobuf.ByteString
        getIpBytes();

    /**
     * <code>required int32 port = 3;</code>
     *
     * <pre>
     *端口号
     * </pre>
     */
    boolean hasPort();
    /**
     * <code>required int32 port = 3;</code>
     *
     * <pre>
     *端口号
     * </pre>
     */
    int getPort();
  }
  /**
   * Protobuf type {@code BF.AgentMaster.AgentAskWorkRsp}
   */
  public static final class AgentAskWorkRsp extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:BF.AgentMaster.AgentAskWorkRsp)
      AgentAskWorkRspOrBuilder {
    // Use AgentAskWorkRsp.newBuilder() to construct.
    private AgentAskWorkRsp(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AgentAskWorkRsp(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AgentAskWorkRsp defaultInstance;
    public static AgentAskWorkRsp getDefaultInstance() {
      return defaultInstance;
    }

    public AgentAskWorkRsp getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AgentAskWorkRsp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              state_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              ip_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              port_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.benq.csgov2.common.protobuf.BFAgentMaster.internal_static_BF_AgentMaster_AgentAskWorkRsp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.benq.csgov2.common.protobuf.BFAgentMaster.internal_static_BF_AgentMaster_AgentAskWorkRsp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.benq.csgov2.common.protobuf.BFAgentMaster.AgentAskWorkRsp.class, com.benq.csgov2.common.protobuf.BFAgentMaster.AgentAskWorkRsp.Builder.class);
    }

    public static com.google.protobuf.Parser<AgentAskWorkRsp> PARSER =
        new com.google.protobuf.AbstractParser<AgentAskWorkRsp>() {
      public AgentAskWorkRsp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AgentAskWorkRsp(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AgentAskWorkRsp> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int STATE_FIELD_NUMBER = 1;
    private int state_;
    /**
     * <code>required int32 state = 1;</code>
     *
     * <pre>
     *AGENT_ASK_FOR_WORK_ADDRESS_RSP
     * </pre>
     */
    public boolean hasState() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 state = 1;</code>
     *
     * <pre>
     *AGENT_ASK_FOR_WORK_ADDRESS_RSP
     * </pre>
     */
    public int getState() {
      return state_;
    }

    public static final int IP_FIELD_NUMBER = 2;
    private java.lang.Object ip_;
    /**
     * <code>required string ip = 2;</code>
     *
     * <pre>
     *状态：返回0,表示OK,ip和port字段有效(允许使用)
     *返回1，表示版本太低需要升级，但依然可以使用(允许使用)
     *返回2,表示保留字段(密码错误) (禁止使用)
     *返回3，其他错误(禁止使用)
     * </pre>
     */
    public boolean hasIp() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string ip = 2;</code>
     *
     * <pre>
     *状态：返回0,表示OK,ip和port字段有效(允许使用)
     *返回1，表示版本太低需要升级，但依然可以使用(允许使用)
     *返回2,表示保留字段(密码错误) (禁止使用)
     *返回3，其他错误(禁止使用)
     * </pre>
     */
    public java.lang.String getIp() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          ip_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string ip = 2;</code>
     *
     * <pre>
     *状态：返回0,表示OK,ip和port字段有效(允许使用)
     *返回1，表示版本太低需要升级，但依然可以使用(允许使用)
     *返回2,表示保留字段(密码错误) (禁止使用)
     *返回3，其他错误(禁止使用)
     * </pre>
     */
    public com.google.protobuf.ByteString
        getIpBytes() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PORT_FIELD_NUMBER = 3;
    private int port_;
    /**
     * <code>required int32 port = 3;</code>
     *
     * <pre>
     *端口号
     * </pre>
     */
    public boolean hasPort() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 port = 3;</code>
     *
     * <pre>
     *端口号
     * </pre>
     */
    public int getPort() {
      return port_;
    }

    private void initFields() {
      state_ = 0;
      ip_ = "";
      port_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasState()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPort()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, state_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getIpBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, port_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, state_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getIpBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, port_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.benq.csgov2.common.protobuf.BFAgentMaster.AgentAskWorkRsp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.benq.csgov2.common.protobuf.BFAgentMaster.AgentAskWorkRsp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.benq.csgov2.common.protobuf.BFAgentMaster.AgentAskWorkRsp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.benq.csgov2.common.protobuf.BFAgentMaster.AgentAskWorkRsp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.benq.csgov2.common.protobuf.BFAgentMaster.AgentAskWorkRsp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.benq.csgov2.common.protobuf.BFAgentMaster.AgentAskWorkRsp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.benq.csgov2.common.protobuf.BFAgentMaster.AgentAskWorkRsp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.benq.csgov2.common.protobuf.BFAgentMaster.AgentAskWorkRsp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.benq.csgov2.common.protobuf.BFAgentMaster.AgentAskWorkRsp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.benq.csgov2.common.protobuf.BFAgentMaster.AgentAskWorkRsp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.benq.csgov2.common.protobuf.BFAgentMaster.AgentAskWorkRsp prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BF.AgentMaster.AgentAskWorkRsp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BF.AgentMaster.AgentAskWorkRsp)
        com.benq.csgov2.common.protobuf.BFAgentMaster.AgentAskWorkRspOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.benq.csgov2.common.protobuf.BFAgentMaster.internal_static_BF_AgentMaster_AgentAskWorkRsp_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.benq.csgov2.common.protobuf.BFAgentMaster.internal_static_BF_AgentMaster_AgentAskWorkRsp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.benq.csgov2.common.protobuf.BFAgentMaster.AgentAskWorkRsp.class, com.benq.csgov2.common.protobuf.BFAgentMaster.AgentAskWorkRsp.Builder.class);
      }

      // Construct using com.benq.csgov2.common.protobuf.BFAgentMaster.AgentAskWorkRsp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        state_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        ip_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        port_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.benq.csgov2.common.protobuf.BFAgentMaster.internal_static_BF_AgentMaster_AgentAskWorkRsp_descriptor;
      }

      public com.benq.csgov2.common.protobuf.BFAgentMaster.AgentAskWorkRsp getDefaultInstanceForType() {
        return com.benq.csgov2.common.protobuf.BFAgentMaster.AgentAskWorkRsp.getDefaultInstance();
      }

      public com.benq.csgov2.common.protobuf.BFAgentMaster.AgentAskWorkRsp build() {
        com.benq.csgov2.common.protobuf.BFAgentMaster.AgentAskWorkRsp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.benq.csgov2.common.protobuf.BFAgentMaster.AgentAskWorkRsp buildPartial() {
        com.benq.csgov2.common.protobuf.BFAgentMaster.AgentAskWorkRsp result = new com.benq.csgov2.common.protobuf.BFAgentMaster.AgentAskWorkRsp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.state_ = state_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.ip_ = ip_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.port_ = port_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.benq.csgov2.common.protobuf.BFAgentMaster.AgentAskWorkRsp) {
          return mergeFrom((com.benq.csgov2.common.protobuf.BFAgentMaster.AgentAskWorkRsp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.benq.csgov2.common.protobuf.BFAgentMaster.AgentAskWorkRsp other) {
        if (other == com.benq.csgov2.common.protobuf.BFAgentMaster.AgentAskWorkRsp.getDefaultInstance()) return this;
        if (other.hasState()) {
          setState(other.getState());
        }
        if (other.hasIp()) {
          bitField0_ |= 0x00000002;
          ip_ = other.ip_;
          onChanged();
        }
        if (other.hasPort()) {
          setPort(other.getPort());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasState()) {
          
          return false;
        }
        if (!hasIp()) {
          
          return false;
        }
        if (!hasPort()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.benq.csgov2.common.protobuf.BFAgentMaster.AgentAskWorkRsp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.benq.csgov2.common.protobuf.BFAgentMaster.AgentAskWorkRsp) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int state_ ;
      /**
       * <code>required int32 state = 1;</code>
       *
       * <pre>
       *AGENT_ASK_FOR_WORK_ADDRESS_RSP
       * </pre>
       */
      public boolean hasState() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 state = 1;</code>
       *
       * <pre>
       *AGENT_ASK_FOR_WORK_ADDRESS_RSP
       * </pre>
       */
      public int getState() {
        return state_;
      }
      /**
       * <code>required int32 state = 1;</code>
       *
       * <pre>
       *AGENT_ASK_FOR_WORK_ADDRESS_RSP
       * </pre>
       */
      public Builder setState(int value) {
        bitField0_ |= 0x00000001;
        state_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 state = 1;</code>
       *
       * <pre>
       *AGENT_ASK_FOR_WORK_ADDRESS_RSP
       * </pre>
       */
      public Builder clearState() {
        bitField0_ = (bitField0_ & ~0x00000001);
        state_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object ip_ = "";
      /**
       * <code>required string ip = 2;</code>
       *
       * <pre>
       *状态：返回0,表示OK,ip和port字段有效(允许使用)
       *返回1，表示版本太低需要升级，但依然可以使用(允许使用)
       *返回2,表示保留字段(密码错误) (禁止使用)
       *返回3，其他错误(禁止使用)
       * </pre>
       */
      public boolean hasIp() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string ip = 2;</code>
       *
       * <pre>
       *状态：返回0,表示OK,ip和port字段有效(允许使用)
       *返回1，表示版本太低需要升级，但依然可以使用(允许使用)
       *返回2,表示保留字段(密码错误) (禁止使用)
       *返回3，其他错误(禁止使用)
       * </pre>
       */
      public java.lang.String getIp() {
        java.lang.Object ref = ip_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            ip_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string ip = 2;</code>
       *
       * <pre>
       *状态：返回0,表示OK,ip和port字段有效(允许使用)
       *返回1，表示版本太低需要升级，但依然可以使用(允许使用)
       *返回2,表示保留字段(密码错误) (禁止使用)
       *返回3，其他错误(禁止使用)
       * </pre>
       */
      public com.google.protobuf.ByteString
          getIpBytes() {
        java.lang.Object ref = ip_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string ip = 2;</code>
       *
       * <pre>
       *状态：返回0,表示OK,ip和port字段有效(允许使用)
       *返回1，表示版本太低需要升级，但依然可以使用(允许使用)
       *返回2,表示保留字段(密码错误) (禁止使用)
       *返回3，其他错误(禁止使用)
       * </pre>
       */
      public Builder setIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        ip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string ip = 2;</code>
       *
       * <pre>
       *状态：返回0,表示OK,ip和port字段有效(允许使用)
       *返回1，表示版本太低需要升级，但依然可以使用(允许使用)
       *返回2,表示保留字段(密码错误) (禁止使用)
       *返回3，其他错误(禁止使用)
       * </pre>
       */
      public Builder clearIp() {
        bitField0_ = (bitField0_ & ~0x00000002);
        ip_ = getDefaultInstance().getIp();
        onChanged();
        return this;
      }
      /**
       * <code>required string ip = 2;</code>
       *
       * <pre>
       *状态：返回0,表示OK,ip和port字段有效(允许使用)
       *返回1，表示版本太低需要升级，但依然可以使用(允许使用)
       *返回2,表示保留字段(密码错误) (禁止使用)
       *返回3，其他错误(禁止使用)
       * </pre>
       */
      public Builder setIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        ip_ = value;
        onChanged();
        return this;
      }

      private int port_ ;
      /**
       * <code>required int32 port = 3;</code>
       *
       * <pre>
       *端口号
       * </pre>
       */
      public boolean hasPort() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 port = 3;</code>
       *
       * <pre>
       *端口号
       * </pre>
       */
      public int getPort() {
        return port_;
      }
      /**
       * <code>required int32 port = 3;</code>
       *
       * <pre>
       *端口号
       * </pre>
       */
      public Builder setPort(int value) {
        bitField0_ |= 0x00000004;
        port_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 port = 3;</code>
       *
       * <pre>
       *端口号
       * </pre>
       */
      public Builder clearPort() {
        bitField0_ = (bitField0_ & ~0x00000004);
        port_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:BF.AgentMaster.AgentAskWorkRsp)
    }

    static {
      defaultInstance = new AgentAskWorkRsp(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:BF.AgentMaster.AgentAskWorkRsp)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BF_AgentMaster_VerStruct_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BF_AgentMaster_VerStruct_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BF_AgentMaster_AgentAskWorkReq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BF_AgentMaster_AgentAskWorkReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BF_AgentMaster_AgentAskWorkRsp_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BF_AgentMaster_AgentAskWorkRsp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024BF.AgentMaster.proto\022\016BF.AgentMaster\"f" +
      "\n\tVerStruct\022\021\n\tiFrameVer\030\001 \002(\005\022\017\n\007iSubVe" +
      "r\030\002 \002(\005\022\022\n\niUpdateVer\030\003 \002(\005\022\021\n\tiBuildVer" +
      "\030\004 \002(\005\022\016\n\006AppVer\030\005 \002(\t\"S\n\017AgentAskWorkRe" +
      "q\022/\n\014AppVerStruct\030\001 \002(\0132\031.BF.AgentMaster" +
      ".VerStruct\022\017\n\007reserve\030\002 \002(\t\":\n\017AgentAskW" +
      "orkRsp\022\r\n\005state\030\001 \002(\005\022\n\n\002ip\030\002 \002(\t\022\014\n\004por" +
      "t\030\003 \002(\005B!\n\037com.benq.csgov2.common.protob" +
      "uf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_BF_AgentMaster_VerStruct_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_BF_AgentMaster_VerStruct_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_BF_AgentMaster_VerStruct_descriptor,
        new java.lang.String[] { "IFrameVer", "ISubVer", "IUpdateVer", "IBuildVer", "AppVer", });
    internal_static_BF_AgentMaster_AgentAskWorkReq_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_BF_AgentMaster_AgentAskWorkReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_BF_AgentMaster_AgentAskWorkReq_descriptor,
        new java.lang.String[] { "AppVerStruct", "Reserve", });
    internal_static_BF_AgentMaster_AgentAskWorkRsp_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_BF_AgentMaster_AgentAskWorkRsp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_BF_AgentMaster_AgentAskWorkRsp_descriptor,
        new java.lang.String[] { "State", "Ip", "Port", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
