// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mode/ServiceMessage.proto

package ritmov2.derek.com.ritemov2.message;

public final class ServiceMessage {
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_structure_Message_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_structure_Message_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n\031mode/ServiceMessage.proto\022\tstructure\"/" +
                        "\n\007Message\022\023\n\013messagetype\030\001 \002(\r\022\017\n\007conten" +
                        "t\030\002 \002(\tB&\n\"ritmov2.derek.com.ritemov2.me" +
                        "ssageH\001"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_structure_Message_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_structure_Message_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_structure_Message_descriptor,
                new String[]{"Messagetype", "Content",});
    }

    private ServiceMessage() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    public interface MessageOrBuilder extends
            // @@protoc_insertion_point(interface_extends:structure.Message)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>required uint32 messagetype = 1;</code>
         */
        boolean hasMessagetype();

        /**
         * <code>required uint32 messagetype = 1;</code>
         */
        int getMessagetype();

        /**
         * <code>required string content = 2;</code>
         */
        boolean hasContent();

        /**
         * <code>required string content = 2;</code>
         */
        String getContent();

        /**
         * <code>required string content = 2;</code>
         */
        com.google.protobuf.ByteString
        getContentBytes();
    }

    /**
     * Protobuf type {@code structure.Message}
     */
    public static final class Message extends
            com.google.protobuf.GeneratedMessage implements
            // @@protoc_insertion_point(message_implements:structure.Message)
            MessageOrBuilder {
        public static final int MESSAGETYPE_FIELD_NUMBER = 1;
        public static final int CONTENT_FIELD_NUMBER = 2;
        private static final Message defaultInstance;
        private static final long serialVersionUID = 0L;
        public static com.google.protobuf.Parser<Message> PARSER =
                new com.google.protobuf.AbstractParser<Message>() {
                    public Message parsePartialFrom(
                            com.google.protobuf.CodedInputStream input,
                            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws com.google.protobuf.InvalidProtocolBufferException {
                        return new Message(input, extensionRegistry);
                    }
                };

        static {
            defaultInstance = new Message(true);
            defaultInstance.initFields();
        }

        private final com.google.protobuf.UnknownFieldSet unknownFields;
        private int bitField0_;
        private int messagetype_;
        private Object content_;
        private byte memoizedIsInitialized = -1;
        private int memoizedSerializedSize = -1;

        // Use Message.newBuilder() to construct.
        private Message(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
            this.unknownFields = builder.getUnknownFields();
        }
        private Message(boolean noInit) {
            this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }
        private Message(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            initFields();
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {
                            bitField0_ |= 0x00000001;
                            messagetype_ = input.readUInt32();
                            break;
                        }
                        case 18: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000002;
                            content_ = bs;
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e.getMessage()).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static Message getDefaultInstance() {
            return defaultInstance;
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return internal_static_structure_Message_descriptor;
        }

        public static ritmov2.derek.com.ritemov2.message.ServiceMessage.Message parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static ritmov2.derek.com.ritemov2.message.ServiceMessage.Message parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static ritmov2.derek.com.ritemov2.message.ServiceMessage.Message parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static ritmov2.derek.com.ritemov2.message.ServiceMessage.Message parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static ritmov2.derek.com.ritemov2.message.ServiceMessage.Message parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static ritmov2.derek.com.ritemov2.message.ServiceMessage.Message parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static ritmov2.derek.com.ritemov2.message.ServiceMessage.Message parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }

        public static ritmov2.derek.com.ritemov2.message.ServiceMessage.Message parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }

        public static ritmov2.derek.com.ritemov2.message.ServiceMessage.Message parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static ritmov2.derek.com.ritemov2.message.ServiceMessage.Message parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public static Builder newBuilder(ritmov2.derek.com.ritemov2.message.ServiceMessage.Message prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public Message getDefaultInstanceForType() {
            return defaultInstance;
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return internal_static_structure_Message_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            ritmov2.derek.com.ritemov2.message.ServiceMessage.Message.class, ritmov2.derek.com.ritemov2.message.ServiceMessage.Message.Builder.class);
        }

        @Override
        public com.google.protobuf.Parser<Message> getParserForType() {
            return PARSER;
        }

        /**
         * <code>required uint32 messagetype = 1;</code>
         */
        public boolean hasMessagetype() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>required uint32 messagetype = 1;</code>
         */
        public int getMessagetype() {
            return messagetype_;
        }

        /**
         * <code>required string content = 2;</code>
         */
        public boolean hasContent() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        /**
         * <code>required string content = 2;</code>
         */
        public String getContent() {
            Object ref = content_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    content_ = s;
                }
                return s;
            }
        }

        /**
         * <code>required string content = 2;</code>
         */
        public com.google.protobuf.ByteString
        getContentBytes() {
            Object ref = content_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                content_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private void initFields() {
            messagetype_ = 0;
            content_ = "";
        }

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            if (!hasMessagetype()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasContent()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeUInt32(1, messagetype_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeBytes(2, getContentBytes());
            }
            getUnknownFields().writeTo(output);
        }

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt32Size(1, messagetype_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(2, getContentBytes());
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        @Override
        protected Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        @Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code structure.Message}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:structure.Message)
                ritmov2.derek.com.ritemov2.message.ServiceMessage.MessageOrBuilder {
            private int bitField0_;
            private int messagetype_;
            private Object content_ = "";

            // Construct using ritmov2.derek.com.ritemov2.message.ServiceMessage.Message.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return internal_static_structure_Message_descriptor;
            }

            private static Builder create() {
                return new Builder();
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return internal_static_structure_Message_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                ritmov2.derek.com.ritemov2.message.ServiceMessage.Message.class, ritmov2.derek.com.ritemov2.message.ServiceMessage.Message.Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                messagetype_ = 0;
                bitField0_ = (bitField0_ & ~0x00000001);
                content_ = "";
                bitField0_ = (bitField0_ & ~0x00000002);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return internal_static_structure_Message_descriptor;
            }

            public ritmov2.derek.com.ritemov2.message.ServiceMessage.Message getDefaultInstanceForType() {
                return getDefaultInstance();
            }

            public ritmov2.derek.com.ritemov2.message.ServiceMessage.Message build() {
                ritmov2.derek.com.ritemov2.message.ServiceMessage.Message result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public ritmov2.derek.com.ritemov2.message.ServiceMessage.Message buildPartial() {
                ritmov2.derek.com.ritemov2.message.ServiceMessage.Message result = new ritmov2.derek.com.ritemov2.message.ServiceMessage.Message(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.messagetype_ = messagetype_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.content_ = content_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof ritmov2.derek.com.ritemov2.message.ServiceMessage.Message) {
                    return mergeFrom((ritmov2.derek.com.ritemov2.message.ServiceMessage.Message) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(ritmov2.derek.com.ritemov2.message.ServiceMessage.Message other) {
                if (other == getDefaultInstance())
                    return this;
                if (other.hasMessagetype()) {
                    setMessagetype(other.getMessagetype());
                }
                if (other.hasContent()) {
                    bitField0_ |= 0x00000002;
                    content_ = other.content_;
                    onChanged();
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                if (!hasMessagetype()) {

                    return false;
                }
                if (!hasContent()) {

                    return false;
                }
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                ritmov2.derek.com.ritemov2.message.ServiceMessage.Message parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (ritmov2.derek.com.ritemov2.message.ServiceMessage.Message) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            /**
             * <code>required uint32 messagetype = 1;</code>
             */
            public boolean hasMessagetype() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>required uint32 messagetype = 1;</code>
             */
            public int getMessagetype() {
                return messagetype_;
            }

            /**
             * <code>required uint32 messagetype = 1;</code>
             */
            public Builder setMessagetype(int value) {
                bitField0_ |= 0x00000001;
                messagetype_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required uint32 messagetype = 1;</code>
             */
            public Builder clearMessagetype() {
                bitField0_ = (bitField0_ & ~0x00000001);
                messagetype_ = 0;
                onChanged();
                return this;
            }

            /**
             * <code>required string content = 2;</code>
             */
            public boolean hasContent() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            /**
             * <code>required string content = 2;</code>
             */
            public String getContent() {
                Object ref = content_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        content_ = s;
                    }
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>required string content = 2;</code>
             */
            public Builder setContent(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                content_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required string content = 2;</code>
             */
            public com.google.protobuf.ByteString
            getContentBytes() {
                Object ref = content_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    content_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>required string content = 2;</code>
             */
            public Builder setContentBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                content_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required string content = 2;</code>
             */
            public Builder clearContent() {
                bitField0_ = (bitField0_ & ~0x00000002);
                content_ = getDefaultInstance().getContent();
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:structure.Message)
        }

        // @@protoc_insertion_point(class_scope:structure.Message)
    }

    // @@protoc_insertion_point(outer_class_scope)
}
