// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BF.Game.proto

package ritemov2.commonModule.protobuf;

public final class BFGame {
  private BFGame() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface GameEnterNotifyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BF.Game.GameEnterNotify)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string serverip = 1;</code>
     *
     * <pre>
     *GAME_ENTER_NOTIFY
     * </pre>
     */
    boolean hasServerip();
    /**
     * <code>required string serverip = 1;</code>
     *
     * <pre>
     *GAME_ENTER_NOTIFY
     * </pre>
     */
    String getServerip();
    /**
     * <code>required string serverip = 1;</code>
     *
     * <pre>
     *GAME_ENTER_NOTIFY
     * </pre>
     */
    com.google.protobuf.ByteString
        getServeripBytes();

    /**
     * <code>required int32 serverport = 2;</code>
     */
    boolean hasServerport();
    /**
     * <code>required int32 serverport = 2;</code>
     */
    int getServerport();
  }
  /**
   * Protobuf type {@code BF.Game.GameEnterNotify}
   */
  public static final class GameEnterNotify extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:BF.Game.GameEnterNotify)
      GameEnterNotifyOrBuilder {
    // Use GameEnterNotify.newBuilder() to construct.
    private GameEnterNotify(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GameEnterNotify(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GameEnterNotify defaultInstance;
    public static GameEnterNotify getDefaultInstance() {
      return defaultInstance;
    }

    public GameEnterNotify getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GameEnterNotify(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              serverip_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              serverport_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ritemov2.commonModule.protobuf.BFGame.internal_static_BF_Game_GameEnterNotify_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ritemov2.commonModule.protobuf.BFGame.internal_static_BF_Game_GameEnterNotify_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ritemov2.commonModule.protobuf.BFGame.GameEnterNotify.class, ritemov2.commonModule.protobuf.BFGame.GameEnterNotify.Builder.class);
    }

    public static com.google.protobuf.Parser<GameEnterNotify> PARSER =
        new com.google.protobuf.AbstractParser<GameEnterNotify>() {
      public GameEnterNotify parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GameEnterNotify(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<GameEnterNotify> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int SERVERIP_FIELD_NUMBER = 1;
    private Object serverip_;
    /**
     * <code>required string serverip = 1;</code>
     *
     * <pre>
     *GAME_ENTER_NOTIFY
     * </pre>
     */
    public boolean hasServerip() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string serverip = 1;</code>
     *
     * <pre>
     *GAME_ENTER_NOTIFY
     * </pre>
     */
    public String getServerip() {
      Object ref = serverip_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          serverip_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string serverip = 1;</code>
     *
     * <pre>
     *GAME_ENTER_NOTIFY
     * </pre>
     */
    public com.google.protobuf.ByteString
        getServeripBytes() {
      Object ref = serverip_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        serverip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SERVERPORT_FIELD_NUMBER = 2;
    private int serverport_;
    /**
     * <code>required int32 serverport = 2;</code>
     */
    public boolean hasServerport() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 serverport = 2;</code>
     */
    public int getServerport() {
      return serverport_;
    }

    private void initFields() {
      serverip_ = "";
      serverport_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasServerip()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasServerport()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getServeripBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, serverport_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getServeripBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, serverport_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ritemov2.commonModule.protobuf.BFGame.GameEnterNotify parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ritemov2.commonModule.protobuf.BFGame.GameEnterNotify parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ritemov2.commonModule.protobuf.BFGame.GameEnterNotify parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ritemov2.commonModule.protobuf.BFGame.GameEnterNotify parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ritemov2.commonModule.protobuf.BFGame.GameEnterNotify parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ritemov2.commonModule.protobuf.BFGame.GameEnterNotify parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ritemov2.commonModule.protobuf.BFGame.GameEnterNotify parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ritemov2.commonModule.protobuf.BFGame.GameEnterNotify parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ritemov2.commonModule.protobuf.BFGame.GameEnterNotify parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ritemov2.commonModule.protobuf.BFGame.GameEnterNotify parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ritemov2.commonModule.protobuf.BFGame.GameEnterNotify prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BF.Game.GameEnterNotify}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BF.Game.GameEnterNotify)
        ritemov2.commonModule.protobuf.BFGame.GameEnterNotifyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ritemov2.commonModule.protobuf.BFGame.internal_static_BF_Game_GameEnterNotify_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ritemov2.commonModule.protobuf.BFGame.internal_static_BF_Game_GameEnterNotify_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ritemov2.commonModule.protobuf.BFGame.GameEnterNotify.class, ritemov2.commonModule.protobuf.BFGame.GameEnterNotify.Builder.class);
      }

      // Construct using ritemov2.commonModule.protobuf.BFGame.GameEnterNotify.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        serverip_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        serverport_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ritemov2.commonModule.protobuf.BFGame.internal_static_BF_Game_GameEnterNotify_descriptor;
      }

      public ritemov2.commonModule.protobuf.BFGame.GameEnterNotify getDefaultInstanceForType() {
        return ritemov2.commonModule.protobuf.BFGame.GameEnterNotify.getDefaultInstance();
      }

      public ritemov2.commonModule.protobuf.BFGame.GameEnterNotify build() {
        ritemov2.commonModule.protobuf.BFGame.GameEnterNotify result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ritemov2.commonModule.protobuf.BFGame.GameEnterNotify buildPartial() {
        ritemov2.commonModule.protobuf.BFGame.GameEnterNotify result = new ritemov2.commonModule.protobuf.BFGame.GameEnterNotify(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.serverip_ = serverip_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.serverport_ = serverport_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ritemov2.commonModule.protobuf.BFGame.GameEnterNotify) {
          return mergeFrom((ritemov2.commonModule.protobuf.BFGame.GameEnterNotify)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ritemov2.commonModule.protobuf.BFGame.GameEnterNotify other) {
        if (other == ritemov2.commonModule.protobuf.BFGame.GameEnterNotify.getDefaultInstance()) return this;
        if (other.hasServerip()) {
          bitField0_ |= 0x00000001;
          serverip_ = other.serverip_;
          onChanged();
        }
        if (other.hasServerport()) {
          setServerport(other.getServerport());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasServerip()) {
          
          return false;
        }
        if (!hasServerport()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ritemov2.commonModule.protobuf.BFGame.GameEnterNotify parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ritemov2.commonModule.protobuf.BFGame.GameEnterNotify) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object serverip_ = "";
      /**
       * <code>required string serverip = 1;</code>
       *
       * <pre>
       *GAME_ENTER_NOTIFY
       * </pre>
       */
      public boolean hasServerip() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string serverip = 1;</code>
       *
       * <pre>
       *GAME_ENTER_NOTIFY
       * </pre>
       */
      public String getServerip() {
        Object ref = serverip_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            serverip_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string serverip = 1;</code>
       *
       * <pre>
       *GAME_ENTER_NOTIFY
       * </pre>
       */
      public com.google.protobuf.ByteString
          getServeripBytes() {
        Object ref = serverip_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          serverip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string serverip = 1;</code>
       *
       * <pre>
       *GAME_ENTER_NOTIFY
       * </pre>
       */
      public Builder setServerip(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        serverip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string serverip = 1;</code>
       *
       * <pre>
       *GAME_ENTER_NOTIFY
       * </pre>
       */
      public Builder clearServerip() {
        bitField0_ = (bitField0_ & ~0x00000001);
        serverip_ = getDefaultInstance().getServerip();
        onChanged();
        return this;
      }
      /**
       * <code>required string serverip = 1;</code>
       *
       * <pre>
       *GAME_ENTER_NOTIFY
       * </pre>
       */
      public Builder setServeripBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        serverip_ = value;
        onChanged();
        return this;
      }

      private int serverport_ ;
      /**
       * <code>required int32 serverport = 2;</code>
       */
      public boolean hasServerport() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 serverport = 2;</code>
       */
      public int getServerport() {
        return serverport_;
      }
      /**
       * <code>required int32 serverport = 2;</code>
       */
      public Builder setServerport(int value) {
        bitField0_ |= 0x00000002;
        serverport_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 serverport = 2;</code>
       */
      public Builder clearServerport() {
        bitField0_ = (bitField0_ & ~0x00000002);
        serverport_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:BF.Game.GameEnterNotify)
    }

    static {
      defaultInstance = new GameEnterNotify(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:BF.Game.GameEnterNotify)
  }

  public interface GameInterruptMessageNotifyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BF.Game.GameInterruptMessageNotify)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .BF.BaseDefine.GameEndType type = 1;</code>
     *
     * <pre>
     *GAME_INTERRUPT_MESSAGE_NOTIFY
     * </pre>
     */
    boolean hasType();
    /**
     * <code>required .BF.BaseDefine.GameEndType type = 1;</code>
     *
     * <pre>
     *GAME_INTERRUPT_MESSAGE_NOTIFY
     * </pre>
     */
    ritemov2.commonModule.protobuf.BFBaseDefine.GameEndType getType();

    /**
     * <code>required int32 steamid = 2;</code>
     */
    boolean hasSteamid();
    /**
     * <code>required int32 steamid = 2;</code>
     */
    int getSteamid();

    /**
     * <code>required int32 matchid = 3;</code>
     */
    boolean hasMatchid();
    /**
     * <code>required int32 matchid = 3;</code>
     */
    int getMatchid();
  }
  /**
   * Protobuf type {@code BF.Game.GameInterruptMessageNotify}
   */
  public static final class GameInterruptMessageNotify extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:BF.Game.GameInterruptMessageNotify)
      GameInterruptMessageNotifyOrBuilder {
    // Use GameInterruptMessageNotify.newBuilder() to construct.
    private GameInterruptMessageNotify(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GameInterruptMessageNotify(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GameInterruptMessageNotify defaultInstance;
    public static GameInterruptMessageNotify getDefaultInstance() {
      return defaultInstance;
    }

    public GameInterruptMessageNotify getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GameInterruptMessageNotify(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              ritemov2.commonModule.protobuf.BFBaseDefine.GameEndType value = ritemov2.commonModule.protobuf.BFBaseDefine.GameEndType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              steamid_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              matchid_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ritemov2.commonModule.protobuf.BFGame.internal_static_BF_Game_GameInterruptMessageNotify_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ritemov2.commonModule.protobuf.BFGame.internal_static_BF_Game_GameInterruptMessageNotify_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ritemov2.commonModule.protobuf.BFGame.GameInterruptMessageNotify.class, ritemov2.commonModule.protobuf.BFGame.GameInterruptMessageNotify.Builder.class);
    }

    public static com.google.protobuf.Parser<GameInterruptMessageNotify> PARSER =
        new com.google.protobuf.AbstractParser<GameInterruptMessageNotify>() {
      public GameInterruptMessageNotify parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GameInterruptMessageNotify(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<GameInterruptMessageNotify> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private ritemov2.commonModule.protobuf.BFBaseDefine.GameEndType type_;
    /**
     * <code>required .BF.BaseDefine.GameEndType type = 1;</code>
     *
     * <pre>
     *GAME_INTERRUPT_MESSAGE_NOTIFY
     * </pre>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .BF.BaseDefine.GameEndType type = 1;</code>
     *
     * <pre>
     *GAME_INTERRUPT_MESSAGE_NOTIFY
     * </pre>
     */
    public ritemov2.commonModule.protobuf.BFBaseDefine.GameEndType getType() {
      return type_;
    }

    public static final int STEAMID_FIELD_NUMBER = 2;
    private int steamid_;
    /**
     * <code>required int32 steamid = 2;</code>
     */
    public boolean hasSteamid() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 steamid = 2;</code>
     */
    public int getSteamid() {
      return steamid_;
    }

    public static final int MATCHID_FIELD_NUMBER = 3;
    private int matchid_;
    /**
     * <code>required int32 matchid = 3;</code>
     */
    public boolean hasMatchid() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 matchid = 3;</code>
     */
    public int getMatchid() {
      return matchid_;
    }

    private void initFields() {
      type_ = ritemov2.commonModule.protobuf.BFBaseDefine.GameEndType.GAMEENDTYPE_NORMAL_END;
      steamid_ = 0;
      matchid_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSteamid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMatchid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, steamid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, matchid_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, steamid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, matchid_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ritemov2.commonModule.protobuf.BFGame.GameInterruptMessageNotify parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ritemov2.commonModule.protobuf.BFGame.GameInterruptMessageNotify parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ritemov2.commonModule.protobuf.BFGame.GameInterruptMessageNotify parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ritemov2.commonModule.protobuf.BFGame.GameInterruptMessageNotify parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ritemov2.commonModule.protobuf.BFGame.GameInterruptMessageNotify parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ritemov2.commonModule.protobuf.BFGame.GameInterruptMessageNotify parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ritemov2.commonModule.protobuf.BFGame.GameInterruptMessageNotify parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ritemov2.commonModule.protobuf.BFGame.GameInterruptMessageNotify parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ritemov2.commonModule.protobuf.BFGame.GameInterruptMessageNotify parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ritemov2.commonModule.protobuf.BFGame.GameInterruptMessageNotify parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ritemov2.commonModule.protobuf.BFGame.GameInterruptMessageNotify prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BF.Game.GameInterruptMessageNotify}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BF.Game.GameInterruptMessageNotify)
        ritemov2.commonModule.protobuf.BFGame.GameInterruptMessageNotifyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ritemov2.commonModule.protobuf.BFGame.internal_static_BF_Game_GameInterruptMessageNotify_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ritemov2.commonModule.protobuf.BFGame.internal_static_BF_Game_GameInterruptMessageNotify_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ritemov2.commonModule.protobuf.BFGame.GameInterruptMessageNotify.class, ritemov2.commonModule.protobuf.BFGame.GameInterruptMessageNotify.Builder.class);
      }

      // Construct using ritemov2.commonModule.protobuf.BFGame.GameInterruptMessageNotify.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = ritemov2.commonModule.protobuf.BFBaseDefine.GameEndType.GAMEENDTYPE_NORMAL_END;
        bitField0_ = (bitField0_ & ~0x00000001);
        steamid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        matchid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ritemov2.commonModule.protobuf.BFGame.internal_static_BF_Game_GameInterruptMessageNotify_descriptor;
      }

      public ritemov2.commonModule.protobuf.BFGame.GameInterruptMessageNotify getDefaultInstanceForType() {
        return ritemov2.commonModule.protobuf.BFGame.GameInterruptMessageNotify.getDefaultInstance();
      }

      public ritemov2.commonModule.protobuf.BFGame.GameInterruptMessageNotify build() {
        ritemov2.commonModule.protobuf.BFGame.GameInterruptMessageNotify result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ritemov2.commonModule.protobuf.BFGame.GameInterruptMessageNotify buildPartial() {
        ritemov2.commonModule.protobuf.BFGame.GameInterruptMessageNotify result = new ritemov2.commonModule.protobuf.BFGame.GameInterruptMessageNotify(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.steamid_ = steamid_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.matchid_ = matchid_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ritemov2.commonModule.protobuf.BFGame.GameInterruptMessageNotify) {
          return mergeFrom((ritemov2.commonModule.protobuf.BFGame.GameInterruptMessageNotify)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ritemov2.commonModule.protobuf.BFGame.GameInterruptMessageNotify other) {
        if (other == ritemov2.commonModule.protobuf.BFGame.GameInterruptMessageNotify.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasSteamid()) {
          setSteamid(other.getSteamid());
        }
        if (other.hasMatchid()) {
          setMatchid(other.getMatchid());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (!hasSteamid()) {
          
          return false;
        }
        if (!hasMatchid()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ritemov2.commonModule.protobuf.BFGame.GameInterruptMessageNotify parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ritemov2.commonModule.protobuf.BFGame.GameInterruptMessageNotify) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private ritemov2.commonModule.protobuf.BFBaseDefine.GameEndType type_ = ritemov2.commonModule.protobuf.BFBaseDefine.GameEndType.GAMEENDTYPE_NORMAL_END;
      /**
       * <code>required .BF.BaseDefine.GameEndType type = 1;</code>
       *
       * <pre>
       *GAME_INTERRUPT_MESSAGE_NOTIFY
       * </pre>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .BF.BaseDefine.GameEndType type = 1;</code>
       *
       * <pre>
       *GAME_INTERRUPT_MESSAGE_NOTIFY
       * </pre>
       */
      public ritemov2.commonModule.protobuf.BFBaseDefine.GameEndType getType() {
        return type_;
      }
      /**
       * <code>required .BF.BaseDefine.GameEndType type = 1;</code>
       *
       * <pre>
       *GAME_INTERRUPT_MESSAGE_NOTIFY
       * </pre>
       */
      public Builder setType(ritemov2.commonModule.protobuf.BFBaseDefine.GameEndType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .BF.BaseDefine.GameEndType type = 1;</code>
       *
       * <pre>
       *GAME_INTERRUPT_MESSAGE_NOTIFY
       * </pre>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = ritemov2.commonModule.protobuf.BFBaseDefine.GameEndType.GAMEENDTYPE_NORMAL_END;
        onChanged();
        return this;
      }

      private int steamid_ ;
      /**
       * <code>required int32 steamid = 2;</code>
       */
      public boolean hasSteamid() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 steamid = 2;</code>
       */
      public int getSteamid() {
        return steamid_;
      }
      /**
       * <code>required int32 steamid = 2;</code>
       */
      public Builder setSteamid(int value) {
        bitField0_ |= 0x00000002;
        steamid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 steamid = 2;</code>
       */
      public Builder clearSteamid() {
        bitField0_ = (bitField0_ & ~0x00000002);
        steamid_ = 0;
        onChanged();
        return this;
      }

      private int matchid_ ;
      /**
       * <code>required int32 matchid = 3;</code>
       */
      public boolean hasMatchid() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 matchid = 3;</code>
       */
      public int getMatchid() {
        return matchid_;
      }
      /**
       * <code>required int32 matchid = 3;</code>
       */
      public Builder setMatchid(int value) {
        bitField0_ |= 0x00000004;
        matchid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 matchid = 3;</code>
       */
      public Builder clearMatchid() {
        bitField0_ = (bitField0_ & ~0x00000004);
        matchid_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:BF.Game.GameInterruptMessageNotify)
    }

    static {
      defaultInstance = new GameInterruptMessageNotify(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:BF.Game.GameInterruptMessageNotify)
  }

  public interface GameDeductScoreReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BF.Game.GameDeductScoreReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 steamid = 1;</code>
     *
     * <pre>
     *GAME_DEDUCT_SCORE_REQ
     * </pre>
     */
    boolean hasSteamid();
    /**
     * <code>required int32 steamid = 1;</code>
     *
     * <pre>
     *GAME_DEDUCT_SCORE_REQ
     * </pre>
     */
    int getSteamid();

    /**
     * <code>required int32 type = 2;</code>
     */
    boolean hasType();
    /**
     * <code>required int32 type = 2;</code>
     */
    int getType();
  }
  /**
   * Protobuf type {@code BF.Game.GameDeductScoreReq}
   */
  public static final class GameDeductScoreReq extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:BF.Game.GameDeductScoreReq)
      GameDeductScoreReqOrBuilder {
    // Use GameDeductScoreReq.newBuilder() to construct.
    private GameDeductScoreReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GameDeductScoreReq(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GameDeductScoreReq defaultInstance;
    public static GameDeductScoreReq getDefaultInstance() {
      return defaultInstance;
    }

    public GameDeductScoreReq getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GameDeductScoreReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              steamid_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              type_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ritemov2.commonModule.protobuf.BFGame.internal_static_BF_Game_GameDeductScoreReq_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ritemov2.commonModule.protobuf.BFGame.internal_static_BF_Game_GameDeductScoreReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ritemov2.commonModule.protobuf.BFGame.GameDeductScoreReq.class, ritemov2.commonModule.protobuf.BFGame.GameDeductScoreReq.Builder.class);
    }

    public static com.google.protobuf.Parser<GameDeductScoreReq> PARSER =
        new com.google.protobuf.AbstractParser<GameDeductScoreReq>() {
      public GameDeductScoreReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GameDeductScoreReq(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<GameDeductScoreReq> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int STEAMID_FIELD_NUMBER = 1;
    private int steamid_;
    /**
     * <code>required int32 steamid = 1;</code>
     *
     * <pre>
     *GAME_DEDUCT_SCORE_REQ
     * </pre>
     */
    public boolean hasSteamid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 steamid = 1;</code>
     *
     * <pre>
     *GAME_DEDUCT_SCORE_REQ
     * </pre>
     */
    public int getSteamid() {
      return steamid_;
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    /**
     * <code>required int32 type = 2;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 type = 2;</code>
     */
    public int getType() {
      return type_;
    }

    private void initFields() {
      steamid_ = 0;
      type_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasSteamid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, steamid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, type_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, steamid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, type_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ritemov2.commonModule.protobuf.BFGame.GameDeductScoreReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ritemov2.commonModule.protobuf.BFGame.GameDeductScoreReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ritemov2.commonModule.protobuf.BFGame.GameDeductScoreReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ritemov2.commonModule.protobuf.BFGame.GameDeductScoreReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ritemov2.commonModule.protobuf.BFGame.GameDeductScoreReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ritemov2.commonModule.protobuf.BFGame.GameDeductScoreReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ritemov2.commonModule.protobuf.BFGame.GameDeductScoreReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ritemov2.commonModule.protobuf.BFGame.GameDeductScoreReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ritemov2.commonModule.protobuf.BFGame.GameDeductScoreReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ritemov2.commonModule.protobuf.BFGame.GameDeductScoreReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ritemov2.commonModule.protobuf.BFGame.GameDeductScoreReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BF.Game.GameDeductScoreReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BF.Game.GameDeductScoreReq)
        ritemov2.commonModule.protobuf.BFGame.GameDeductScoreReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ritemov2.commonModule.protobuf.BFGame.internal_static_BF_Game_GameDeductScoreReq_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ritemov2.commonModule.protobuf.BFGame.internal_static_BF_Game_GameDeductScoreReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ritemov2.commonModule.protobuf.BFGame.GameDeductScoreReq.class, ritemov2.commonModule.protobuf.BFGame.GameDeductScoreReq.Builder.class);
      }

      // Construct using ritemov2.commonModule.protobuf.BFGame.GameDeductScoreReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        steamid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ritemov2.commonModule.protobuf.BFGame.internal_static_BF_Game_GameDeductScoreReq_descriptor;
      }

      public ritemov2.commonModule.protobuf.BFGame.GameDeductScoreReq getDefaultInstanceForType() {
        return ritemov2.commonModule.protobuf.BFGame.GameDeductScoreReq.getDefaultInstance();
      }

      public ritemov2.commonModule.protobuf.BFGame.GameDeductScoreReq build() {
        ritemov2.commonModule.protobuf.BFGame.GameDeductScoreReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ritemov2.commonModule.protobuf.BFGame.GameDeductScoreReq buildPartial() {
        ritemov2.commonModule.protobuf.BFGame.GameDeductScoreReq result = new ritemov2.commonModule.protobuf.BFGame.GameDeductScoreReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.steamid_ = steamid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.type_ = type_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ritemov2.commonModule.protobuf.BFGame.GameDeductScoreReq) {
          return mergeFrom((ritemov2.commonModule.protobuf.BFGame.GameDeductScoreReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ritemov2.commonModule.protobuf.BFGame.GameDeductScoreReq other) {
        if (other == ritemov2.commonModule.protobuf.BFGame.GameDeductScoreReq.getDefaultInstance()) return this;
        if (other.hasSteamid()) {
          setSteamid(other.getSteamid());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSteamid()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ritemov2.commonModule.protobuf.BFGame.GameDeductScoreReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ritemov2.commonModule.protobuf.BFGame.GameDeductScoreReq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int steamid_ ;
      /**
       * <code>required int32 steamid = 1;</code>
       *
       * <pre>
       *GAME_DEDUCT_SCORE_REQ
       * </pre>
       */
      public boolean hasSteamid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 steamid = 1;</code>
       *
       * <pre>
       *GAME_DEDUCT_SCORE_REQ
       * </pre>
       */
      public int getSteamid() {
        return steamid_;
      }
      /**
       * <code>required int32 steamid = 1;</code>
       *
       * <pre>
       *GAME_DEDUCT_SCORE_REQ
       * </pre>
       */
      public Builder setSteamid(int value) {
        bitField0_ |= 0x00000001;
        steamid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 steamid = 1;</code>
       *
       * <pre>
       *GAME_DEDUCT_SCORE_REQ
       * </pre>
       */
      public Builder clearSteamid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        steamid_ = 0;
        onChanged();
        return this;
      }

      private int type_ ;
      /**
       * <code>required int32 type = 2;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 type = 2;</code>
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>required int32 type = 2;</code>
       */
      public Builder setType(int value) {
        bitField0_ |= 0x00000002;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 type = 2;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:BF.Game.GameDeductScoreReq)
    }

    static {
      defaultInstance = new GameDeductScoreReq(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:BF.Game.GameDeductScoreReq)
  }

  public interface GameOverNotifyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BF.Game.GameOverNotify)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 matchid = 1;</code>
     *
     * <pre>
     *GAME_OVER_NOTIFY
     * </pre>
     */
    boolean hasMatchid();
    /**
     * <code>required int32 matchid = 1;</code>
     *
     * <pre>
     *GAME_OVER_NOTIFY
     * </pre>
     */
    int getMatchid();
  }
  /**
   * Protobuf type {@code BF.Game.GameOverNotify}
   */
  public static final class GameOverNotify extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:BF.Game.GameOverNotify)
      GameOverNotifyOrBuilder {
    // Use GameOverNotify.newBuilder() to construct.
    private GameOverNotify(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GameOverNotify(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GameOverNotify defaultInstance;
    public static GameOverNotify getDefaultInstance() {
      return defaultInstance;
    }

    public GameOverNotify getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GameOverNotify(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              matchid_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ritemov2.commonModule.protobuf.BFGame.internal_static_BF_Game_GameOverNotify_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ritemov2.commonModule.protobuf.BFGame.internal_static_BF_Game_GameOverNotify_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ritemov2.commonModule.protobuf.BFGame.GameOverNotify.class, ritemov2.commonModule.protobuf.BFGame.GameOverNotify.Builder.class);
    }

    public static com.google.protobuf.Parser<GameOverNotify> PARSER =
        new com.google.protobuf.AbstractParser<GameOverNotify>() {
      public GameOverNotify parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GameOverNotify(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<GameOverNotify> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int MATCHID_FIELD_NUMBER = 1;
    private int matchid_;
    /**
     * <code>required int32 matchid = 1;</code>
     *
     * <pre>
     *GAME_OVER_NOTIFY
     * </pre>
     */
    public boolean hasMatchid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 matchid = 1;</code>
     *
     * <pre>
     *GAME_OVER_NOTIFY
     * </pre>
     */
    public int getMatchid() {
      return matchid_;
    }

    private void initFields() {
      matchid_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasMatchid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, matchid_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, matchid_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ritemov2.commonModule.protobuf.BFGame.GameOverNotify parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ritemov2.commonModule.protobuf.BFGame.GameOverNotify parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ritemov2.commonModule.protobuf.BFGame.GameOverNotify parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ritemov2.commonModule.protobuf.BFGame.GameOverNotify parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ritemov2.commonModule.protobuf.BFGame.GameOverNotify parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ritemov2.commonModule.protobuf.BFGame.GameOverNotify parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ritemov2.commonModule.protobuf.BFGame.GameOverNotify parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ritemov2.commonModule.protobuf.BFGame.GameOverNotify parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ritemov2.commonModule.protobuf.BFGame.GameOverNotify parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ritemov2.commonModule.protobuf.BFGame.GameOverNotify parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ritemov2.commonModule.protobuf.BFGame.GameOverNotify prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BF.Game.GameOverNotify}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BF.Game.GameOverNotify)
        ritemov2.commonModule.protobuf.BFGame.GameOverNotifyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ritemov2.commonModule.protobuf.BFGame.internal_static_BF_Game_GameOverNotify_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ritemov2.commonModule.protobuf.BFGame.internal_static_BF_Game_GameOverNotify_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ritemov2.commonModule.protobuf.BFGame.GameOverNotify.class, ritemov2.commonModule.protobuf.BFGame.GameOverNotify.Builder.class);
      }

      // Construct using ritemov2.commonModule.protobuf.BFGame.GameOverNotify.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        matchid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ritemov2.commonModule.protobuf.BFGame.internal_static_BF_Game_GameOverNotify_descriptor;
      }

      public ritemov2.commonModule.protobuf.BFGame.GameOverNotify getDefaultInstanceForType() {
        return ritemov2.commonModule.protobuf.BFGame.GameOverNotify.getDefaultInstance();
      }

      public ritemov2.commonModule.protobuf.BFGame.GameOverNotify build() {
        ritemov2.commonModule.protobuf.BFGame.GameOverNotify result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ritemov2.commonModule.protobuf.BFGame.GameOverNotify buildPartial() {
        ritemov2.commonModule.protobuf.BFGame.GameOverNotify result = new ritemov2.commonModule.protobuf.BFGame.GameOverNotify(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.matchid_ = matchid_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ritemov2.commonModule.protobuf.BFGame.GameOverNotify) {
          return mergeFrom((ritemov2.commonModule.protobuf.BFGame.GameOverNotify)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ritemov2.commonModule.protobuf.BFGame.GameOverNotify other) {
        if (other == ritemov2.commonModule.protobuf.BFGame.GameOverNotify.getDefaultInstance()) return this;
        if (other.hasMatchid()) {
          setMatchid(other.getMatchid());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMatchid()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ritemov2.commonModule.protobuf.BFGame.GameOverNotify parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ritemov2.commonModule.protobuf.BFGame.GameOverNotify) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int matchid_ ;
      /**
       * <code>required int32 matchid = 1;</code>
       *
       * <pre>
       *GAME_OVER_NOTIFY
       * </pre>
       */
      public boolean hasMatchid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 matchid = 1;</code>
       *
       * <pre>
       *GAME_OVER_NOTIFY
       * </pre>
       */
      public int getMatchid() {
        return matchid_;
      }
      /**
       * <code>required int32 matchid = 1;</code>
       *
       * <pre>
       *GAME_OVER_NOTIFY
       * </pre>
       */
      public Builder setMatchid(int value) {
        bitField0_ |= 0x00000001;
        matchid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 matchid = 1;</code>
       *
       * <pre>
       *GAME_OVER_NOTIFY
       * </pre>
       */
      public Builder clearMatchid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        matchid_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:BF.Game.GameOverNotify)
    }

    static {
      defaultInstance = new GameOverNotify(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:BF.Game.GameOverNotify)
  }

  public interface GameScreenShotReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BF.Game.GameScreenShotReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 steamid = 1;</code>
     *
     * <pre>
     *GAME_SCREEN_SHOT_REQ
     * </pre>
     */
    boolean hasSteamid();
    /**
     * <code>required int32 steamid = 1;</code>
     *
     * <pre>
     *GAME_SCREEN_SHOT_REQ
     * </pre>
     */
    int getSteamid();

    /**
     * <code>required int32 targetint = 2;</code>
     *
     * <pre>
     *steamid
     * </pre>
     */
    boolean hasTargetint();
    /**
     * <code>required int32 targetint = 2;</code>
     *
     * <pre>
     *steamid
     * </pre>
     */
    int getTargetint();
  }
  /**
   * Protobuf type {@code BF.Game.GameScreenShotReq}
   */
  public static final class GameScreenShotReq extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:BF.Game.GameScreenShotReq)
      GameScreenShotReqOrBuilder {
    // Use GameScreenShotReq.newBuilder() to construct.
    private GameScreenShotReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GameScreenShotReq(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GameScreenShotReq defaultInstance;
    public static GameScreenShotReq getDefaultInstance() {
      return defaultInstance;
    }

    public GameScreenShotReq getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GameScreenShotReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              steamid_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              targetint_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ritemov2.commonModule.protobuf.BFGame.internal_static_BF_Game_GameScreenShotReq_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ritemov2.commonModule.protobuf.BFGame.internal_static_BF_Game_GameScreenShotReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ritemov2.commonModule.protobuf.BFGame.GameScreenShotReq.class, ritemov2.commonModule.protobuf.BFGame.GameScreenShotReq.Builder.class);
    }

    public static com.google.protobuf.Parser<GameScreenShotReq> PARSER =
        new com.google.protobuf.AbstractParser<GameScreenShotReq>() {
      public GameScreenShotReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GameScreenShotReq(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<GameScreenShotReq> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int STEAMID_FIELD_NUMBER = 1;
    private int steamid_;
    /**
     * <code>required int32 steamid = 1;</code>
     *
     * <pre>
     *GAME_SCREEN_SHOT_REQ
     * </pre>
     */
    public boolean hasSteamid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 steamid = 1;</code>
     *
     * <pre>
     *GAME_SCREEN_SHOT_REQ
     * </pre>
     */
    public int getSteamid() {
      return steamid_;
    }

    public static final int TARGETINT_FIELD_NUMBER = 2;
    private int targetint_;
    /**
     * <code>required int32 targetint = 2;</code>
     *
     * <pre>
     *steamid
     * </pre>
     */
    public boolean hasTargetint() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 targetint = 2;</code>
     *
     * <pre>
     *steamid
     * </pre>
     */
    public int getTargetint() {
      return targetint_;
    }

    private void initFields() {
      steamid_ = 0;
      targetint_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasSteamid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTargetint()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, steamid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, targetint_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, steamid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, targetint_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ritemov2.commonModule.protobuf.BFGame.GameScreenShotReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ritemov2.commonModule.protobuf.BFGame.GameScreenShotReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ritemov2.commonModule.protobuf.BFGame.GameScreenShotReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ritemov2.commonModule.protobuf.BFGame.GameScreenShotReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ritemov2.commonModule.protobuf.BFGame.GameScreenShotReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ritemov2.commonModule.protobuf.BFGame.GameScreenShotReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ritemov2.commonModule.protobuf.BFGame.GameScreenShotReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ritemov2.commonModule.protobuf.BFGame.GameScreenShotReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ritemov2.commonModule.protobuf.BFGame.GameScreenShotReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ritemov2.commonModule.protobuf.BFGame.GameScreenShotReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ritemov2.commonModule.protobuf.BFGame.GameScreenShotReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BF.Game.GameScreenShotReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BF.Game.GameScreenShotReq)
        ritemov2.commonModule.protobuf.BFGame.GameScreenShotReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ritemov2.commonModule.protobuf.BFGame.internal_static_BF_Game_GameScreenShotReq_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ritemov2.commonModule.protobuf.BFGame.internal_static_BF_Game_GameScreenShotReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ritemov2.commonModule.protobuf.BFGame.GameScreenShotReq.class, ritemov2.commonModule.protobuf.BFGame.GameScreenShotReq.Builder.class);
      }

      // Construct using ritemov2.commonModule.protobuf.BFGame.GameScreenShotReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        steamid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        targetint_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ritemov2.commonModule.protobuf.BFGame.internal_static_BF_Game_GameScreenShotReq_descriptor;
      }

      public ritemov2.commonModule.protobuf.BFGame.GameScreenShotReq getDefaultInstanceForType() {
        return ritemov2.commonModule.protobuf.BFGame.GameScreenShotReq.getDefaultInstance();
      }

      public ritemov2.commonModule.protobuf.BFGame.GameScreenShotReq build() {
        ritemov2.commonModule.protobuf.BFGame.GameScreenShotReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ritemov2.commonModule.protobuf.BFGame.GameScreenShotReq buildPartial() {
        ritemov2.commonModule.protobuf.BFGame.GameScreenShotReq result = new ritemov2.commonModule.protobuf.BFGame.GameScreenShotReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.steamid_ = steamid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.targetint_ = targetint_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ritemov2.commonModule.protobuf.BFGame.GameScreenShotReq) {
          return mergeFrom((ritemov2.commonModule.protobuf.BFGame.GameScreenShotReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ritemov2.commonModule.protobuf.BFGame.GameScreenShotReq other) {
        if (other == ritemov2.commonModule.protobuf.BFGame.GameScreenShotReq.getDefaultInstance()) return this;
        if (other.hasSteamid()) {
          setSteamid(other.getSteamid());
        }
        if (other.hasTargetint()) {
          setTargetint(other.getTargetint());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSteamid()) {
          
          return false;
        }
        if (!hasTargetint()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ritemov2.commonModule.protobuf.BFGame.GameScreenShotReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ritemov2.commonModule.protobuf.BFGame.GameScreenShotReq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int steamid_ ;
      /**
       * <code>required int32 steamid = 1;</code>
       *
       * <pre>
       *GAME_SCREEN_SHOT_REQ
       * </pre>
       */
      public boolean hasSteamid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 steamid = 1;</code>
       *
       * <pre>
       *GAME_SCREEN_SHOT_REQ
       * </pre>
       */
      public int getSteamid() {
        return steamid_;
      }
      /**
       * <code>required int32 steamid = 1;</code>
       *
       * <pre>
       *GAME_SCREEN_SHOT_REQ
       * </pre>
       */
      public Builder setSteamid(int value) {
        bitField0_ |= 0x00000001;
        steamid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 steamid = 1;</code>
       *
       * <pre>
       *GAME_SCREEN_SHOT_REQ
       * </pre>
       */
      public Builder clearSteamid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        steamid_ = 0;
        onChanged();
        return this;
      }

      private int targetint_ ;
      /**
       * <code>required int32 targetint = 2;</code>
       *
       * <pre>
       *steamid
       * </pre>
       */
      public boolean hasTargetint() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 targetint = 2;</code>
       *
       * <pre>
       *steamid
       * </pre>
       */
      public int getTargetint() {
        return targetint_;
      }
      /**
       * <code>required int32 targetint = 2;</code>
       *
       * <pre>
       *steamid
       * </pre>
       */
      public Builder setTargetint(int value) {
        bitField0_ |= 0x00000002;
        targetint_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 targetint = 2;</code>
       *
       * <pre>
       *steamid
       * </pre>
       */
      public Builder clearTargetint() {
        bitField0_ = (bitField0_ & ~0x00000002);
        targetint_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:BF.Game.GameScreenShotReq)
    }

    static {
      defaultInstance = new GameScreenShotReq(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:BF.Game.GameScreenShotReq)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BF_Game_GameEnterNotify_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BF_Game_GameEnterNotify_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BF_Game_GameInterruptMessageNotify_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BF_Game_GameInterruptMessageNotify_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BF_Game_GameDeductScoreReq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BF_Game_GameDeductScoreReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BF_Game_GameOverNotify_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BF_Game_GameOverNotify_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BF_Game_GameScreenShotReq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BF_Game_GameScreenShotReq_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rBF.Game.proto\022\007BF.Game\032\023BF.BaseDefine." +
      "proto\"7\n\017GameEnterNotify\022\020\n\010serverip\030\001 \002" +
      "(\t\022\022\n\nserverport\030\002 \002(\005\"h\n\032GameInterruptM" +
      "essageNotify\022(\n\004type\030\001 \002(\0162\032.BF.BaseDefi" +
      "ne.GameEndType\022\017\n\007steamid\030\002 \002(\005\022\017\n\007match" +
      "id\030\003 \002(\005\"3\n\022GameDeductScoreReq\022\017\n\007steami" +
      "d\030\001 \002(\005\022\014\n\004type\030\002 \002(\005\"!\n\016GameOverNotify\022" +
      "\017\n\007matchid\030\001 \002(\005\"7\n\021GameScreenShotReq\022\017\n" +
      "\007steamid\030\001 \002(\005\022\021\n\ttargetint\030\002 \002(\005B!\n\037com" +
      ".benq.csgov2.common.protobuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ritemov2.commonModule.protobuf.BFBaseDefine.getDescriptor(),
        }, assigner);
    internal_static_BF_Game_GameEnterNotify_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_BF_Game_GameEnterNotify_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_BF_Game_GameEnterNotify_descriptor,
        new String[] { "Serverip", "Serverport", });
    internal_static_BF_Game_GameInterruptMessageNotify_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_BF_Game_GameInterruptMessageNotify_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_BF_Game_GameInterruptMessageNotify_descriptor,
        new String[] { "Type", "Steamid", "Matchid", });
    internal_static_BF_Game_GameDeductScoreReq_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_BF_Game_GameDeductScoreReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_BF_Game_GameDeductScoreReq_descriptor,
        new String[] { "Steamid", "Type", });
    internal_static_BF_Game_GameOverNotify_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_BF_Game_GameOverNotify_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_BF_Game_GameOverNotify_descriptor,
        new String[] { "Matchid", });
    internal_static_BF_Game_GameScreenShotReq_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_BF_Game_GameScreenShotReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_BF_Game_GameScreenShotReq_descriptor,
        new String[] { "Steamid", "Targetint", });
    ritemov2.commonModule.protobuf.BFBaseDefine.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
