// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BF.IMMessage.proto

package ritemov2.commonModule.protobuf;

public final class BFIMMessage {
  private BFIMMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ChatSendRoomMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BF.IMMessage.ChatSendRoomMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .BF.BaseDefine.MsgType type = 1;</code>
     *
     * <pre>
     *CHAT_SEND_ROOM_MESSAGE
     * </pre>
     */
    boolean hasType();
    /**
     * <code>required .BF.BaseDefine.MsgType type = 1;</code>
     *
     * <pre>
     *CHAT_SEND_ROOM_MESSAGE
     * </pre>
     */
    ritemov2.commonModule.protobuf.BFBaseDefine.MsgType getType();

    /**
     * <code>required int32 steamid = 2;</code>
     */
    boolean hasSteamid();
    /**
     * <code>required int32 steamid = 2;</code>
     */
    int getSteamid();

    /**
     * <code>required string gameroom = 3;</code>
     */
    boolean hasGameroom();
    /**
     * <code>required string gameroom = 3;</code>
     */
    String getGameroom();
    /**
     * <code>required string gameroom = 3;</code>
     */
    com.google.protobuf.ByteString
        getGameroomBytes();

    /**
     * <code>required string msg = 4;</code>
     */
    boolean hasMsg();
    /**
     * <code>required string msg = 4;</code>
     */
    String getMsg();
    /**
     * <code>required string msg = 4;</code>
     */
    com.google.protobuf.ByteString
        getMsgBytes();
  }
  /**
   * Protobuf type {@code BF.IMMessage.ChatSendRoomMessage}
   */
  public static final class ChatSendRoomMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:BF.IMMessage.ChatSendRoomMessage)
      ChatSendRoomMessageOrBuilder {
    // Use ChatSendRoomMessage.newBuilder() to construct.
    private ChatSendRoomMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ChatSendRoomMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ChatSendRoomMessage defaultInstance;
    public static ChatSendRoomMessage getDefaultInstance() {
      return defaultInstance;
    }

    public ChatSendRoomMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ChatSendRoomMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              ritemov2.commonModule.protobuf.BFBaseDefine.MsgType value = ritemov2.commonModule.protobuf.BFBaseDefine.MsgType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              steamid_ = input.readInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              gameroom_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              msg_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ritemov2.commonModule.protobuf.BFIMMessage.internal_static_BF_IMMessage_ChatSendRoomMessage_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ritemov2.commonModule.protobuf.BFIMMessage.internal_static_BF_IMMessage_ChatSendRoomMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ritemov2.commonModule.protobuf.BFIMMessage.ChatSendRoomMessage.class, ritemov2.commonModule.protobuf.BFIMMessage.ChatSendRoomMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<ChatSendRoomMessage> PARSER =
        new com.google.protobuf.AbstractParser<ChatSendRoomMessage>() {
      public ChatSendRoomMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChatSendRoomMessage(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<ChatSendRoomMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private ritemov2.commonModule.protobuf.BFBaseDefine.MsgType type_;
    /**
     * <code>required .BF.BaseDefine.MsgType type = 1;</code>
     *
     * <pre>
     *CHAT_SEND_ROOM_MESSAGE
     * </pre>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .BF.BaseDefine.MsgType type = 1;</code>
     *
     * <pre>
     *CHAT_SEND_ROOM_MESSAGE
     * </pre>
     */
    public ritemov2.commonModule.protobuf.BFBaseDefine.MsgType getType() {
      return type_;
    }

    public static final int STEAMID_FIELD_NUMBER = 2;
    private int steamid_;
    /**
     * <code>required int32 steamid = 2;</code>
     */
    public boolean hasSteamid() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 steamid = 2;</code>
     */
    public int getSteamid() {
      return steamid_;
    }

    public static final int GAMEROOM_FIELD_NUMBER = 3;
    private Object gameroom_;
    /**
     * <code>required string gameroom = 3;</code>
     */
    public boolean hasGameroom() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string gameroom = 3;</code>
     */
    public String getGameroom() {
      Object ref = gameroom_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          gameroom_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string gameroom = 3;</code>
     */
    public com.google.protobuf.ByteString
        getGameroomBytes() {
      Object ref = gameroom_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        gameroom_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MSG_FIELD_NUMBER = 4;
    private Object msg_;
    /**
     * <code>required string msg = 4;</code>
     */
    public boolean hasMsg() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string msg = 4;</code>
     */
    public String getMsg() {
      Object ref = msg_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string msg = 4;</code>
     */
    public com.google.protobuf.ByteString
        getMsgBytes() {
      Object ref = msg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      type_ = ritemov2.commonModule.protobuf.BFBaseDefine.MsgType.MSG_SYSTEM;
      steamid_ = 0;
      gameroom_ = "";
      msg_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSteamid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasGameroom()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMsg()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, steamid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getGameroomBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getMsgBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, steamid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getGameroomBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getMsgBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ritemov2.commonModule.protobuf.BFIMMessage.ChatSendRoomMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ritemov2.commonModule.protobuf.BFIMMessage.ChatSendRoomMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ritemov2.commonModule.protobuf.BFIMMessage.ChatSendRoomMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ritemov2.commonModule.protobuf.BFIMMessage.ChatSendRoomMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ritemov2.commonModule.protobuf.BFIMMessage.ChatSendRoomMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ritemov2.commonModule.protobuf.BFIMMessage.ChatSendRoomMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ritemov2.commonModule.protobuf.BFIMMessage.ChatSendRoomMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ritemov2.commonModule.protobuf.BFIMMessage.ChatSendRoomMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ritemov2.commonModule.protobuf.BFIMMessage.ChatSendRoomMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ritemov2.commonModule.protobuf.BFIMMessage.ChatSendRoomMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ritemov2.commonModule.protobuf.BFIMMessage.ChatSendRoomMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BF.IMMessage.ChatSendRoomMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BF.IMMessage.ChatSendRoomMessage)
        ritemov2.commonModule.protobuf.BFIMMessage.ChatSendRoomMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ritemov2.commonModule.protobuf.BFIMMessage.internal_static_BF_IMMessage_ChatSendRoomMessage_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ritemov2.commonModule.protobuf.BFIMMessage.internal_static_BF_IMMessage_ChatSendRoomMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ritemov2.commonModule.protobuf.BFIMMessage.ChatSendRoomMessage.class, ritemov2.commonModule.protobuf.BFIMMessage.ChatSendRoomMessage.Builder.class);
      }

      // Construct using ritemov2.commonModule.protobuf.BFIMMessage.ChatSendRoomMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = ritemov2.commonModule.protobuf.BFBaseDefine.MsgType.MSG_SYSTEM;
        bitField0_ = (bitField0_ & ~0x00000001);
        steamid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        gameroom_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        msg_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ritemov2.commonModule.protobuf.BFIMMessage.internal_static_BF_IMMessage_ChatSendRoomMessage_descriptor;
      }

      public ritemov2.commonModule.protobuf.BFIMMessage.ChatSendRoomMessage getDefaultInstanceForType() {
        return ritemov2.commonModule.protobuf.BFIMMessage.ChatSendRoomMessage.getDefaultInstance();
      }

      public ritemov2.commonModule.protobuf.BFIMMessage.ChatSendRoomMessage build() {
        ritemov2.commonModule.protobuf.BFIMMessage.ChatSendRoomMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ritemov2.commonModule.protobuf.BFIMMessage.ChatSendRoomMessage buildPartial() {
        ritemov2.commonModule.protobuf.BFIMMessage.ChatSendRoomMessage result = new ritemov2.commonModule.protobuf.BFIMMessage.ChatSendRoomMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.steamid_ = steamid_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.gameroom_ = gameroom_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.msg_ = msg_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ritemov2.commonModule.protobuf.BFIMMessage.ChatSendRoomMessage) {
          return mergeFrom((ritemov2.commonModule.protobuf.BFIMMessage.ChatSendRoomMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ritemov2.commonModule.protobuf.BFIMMessage.ChatSendRoomMessage other) {
        if (other == ritemov2.commonModule.protobuf.BFIMMessage.ChatSendRoomMessage.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasSteamid()) {
          setSteamid(other.getSteamid());
        }
        if (other.hasGameroom()) {
          bitField0_ |= 0x00000004;
          gameroom_ = other.gameroom_;
          onChanged();
        }
        if (other.hasMsg()) {
          bitField0_ |= 0x00000008;
          msg_ = other.msg_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (!hasSteamid()) {
          
          return false;
        }
        if (!hasGameroom()) {
          
          return false;
        }
        if (!hasMsg()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ritemov2.commonModule.protobuf.BFIMMessage.ChatSendRoomMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ritemov2.commonModule.protobuf.BFIMMessage.ChatSendRoomMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private ritemov2.commonModule.protobuf.BFBaseDefine.MsgType type_ = ritemov2.commonModule.protobuf.BFBaseDefine.MsgType.MSG_SYSTEM;
      /**
       * <code>required .BF.BaseDefine.MsgType type = 1;</code>
       *
       * <pre>
       *CHAT_SEND_ROOM_MESSAGE
       * </pre>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .BF.BaseDefine.MsgType type = 1;</code>
       *
       * <pre>
       *CHAT_SEND_ROOM_MESSAGE
       * </pre>
       */
      public ritemov2.commonModule.protobuf.BFBaseDefine.MsgType getType() {
        return type_;
      }
      /**
       * <code>required .BF.BaseDefine.MsgType type = 1;</code>
       *
       * <pre>
       *CHAT_SEND_ROOM_MESSAGE
       * </pre>
       */
      public Builder setType(ritemov2.commonModule.protobuf.BFBaseDefine.MsgType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .BF.BaseDefine.MsgType type = 1;</code>
       *
       * <pre>
       *CHAT_SEND_ROOM_MESSAGE
       * </pre>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = ritemov2.commonModule.protobuf.BFBaseDefine.MsgType.MSG_SYSTEM;
        onChanged();
        return this;
      }

      private int steamid_ ;
      /**
       * <code>required int32 steamid = 2;</code>
       */
      public boolean hasSteamid() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 steamid = 2;</code>
       */
      public int getSteamid() {
        return steamid_;
      }
      /**
       * <code>required int32 steamid = 2;</code>
       */
      public Builder setSteamid(int value) {
        bitField0_ |= 0x00000002;
        steamid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 steamid = 2;</code>
       */
      public Builder clearSteamid() {
        bitField0_ = (bitField0_ & ~0x00000002);
        steamid_ = 0;
        onChanged();
        return this;
      }

      private Object gameroom_ = "";
      /**
       * <code>required string gameroom = 3;</code>
       */
      public boolean hasGameroom() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string gameroom = 3;</code>
       */
      public String getGameroom() {
        Object ref = gameroom_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            gameroom_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string gameroom = 3;</code>
       */
      public com.google.protobuf.ByteString
          getGameroomBytes() {
        Object ref = gameroom_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          gameroom_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string gameroom = 3;</code>
       */
      public Builder setGameroom(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        gameroom_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string gameroom = 3;</code>
       */
      public Builder clearGameroom() {
        bitField0_ = (bitField0_ & ~0x00000004);
        gameroom_ = getDefaultInstance().getGameroom();
        onChanged();
        return this;
      }
      /**
       * <code>required string gameroom = 3;</code>
       */
      public Builder setGameroomBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        gameroom_ = value;
        onChanged();
        return this;
      }

      private Object msg_ = "";
      /**
       * <code>required string msg = 4;</code>
       */
      public boolean hasMsg() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string msg = 4;</code>
       */
      public String getMsg() {
        Object ref = msg_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            msg_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string msg = 4;</code>
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string msg = 4;</code>
       */
      public Builder setMsg(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string msg = 4;</code>
       */
      public Builder clearMsg() {
        bitField0_ = (bitField0_ & ~0x00000008);
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      /**
       * <code>required string msg = 4;</code>
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        msg_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:BF.IMMessage.ChatSendRoomMessage)
    }

    static {
      defaultInstance = new ChatSendRoomMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:BF.IMMessage.ChatSendRoomMessage)
  }

  public interface ChatRoomMessageNotifyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BF.IMMessage.ChatRoomMessageNotify)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .BF.BaseDefine.MsgType type = 1;</code>
     *
     * <pre>
     *CHAT_ROOM_MESSAGE_NOTIFY
     * </pre>
     */
    boolean hasType();
    /**
     * <code>required .BF.BaseDefine.MsgType type = 1;</code>
     *
     * <pre>
     *CHAT_ROOM_MESSAGE_NOTIFY
     * </pre>
     */
    ritemov2.commonModule.protobuf.BFBaseDefine.MsgType getType();

    /**
     * <code>required int32 steamid = 2;</code>
     */
    boolean hasSteamid();
    /**
     * <code>required int32 steamid = 2;</code>
     */
    int getSteamid();

    /**
     * <code>required string msg = 3;</code>
     */
    boolean hasMsg();
    /**
     * <code>required string msg = 3;</code>
     */
    String getMsg();
    /**
     * <code>required string msg = 3;</code>
     */
    com.google.protobuf.ByteString
        getMsgBytes();
  }
  /**
   * Protobuf type {@code BF.IMMessage.ChatRoomMessageNotify}
   */
  public static final class ChatRoomMessageNotify extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:BF.IMMessage.ChatRoomMessageNotify)
      ChatRoomMessageNotifyOrBuilder {
    // Use ChatRoomMessageNotify.newBuilder() to construct.
    private ChatRoomMessageNotify(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ChatRoomMessageNotify(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ChatRoomMessageNotify defaultInstance;
    public static ChatRoomMessageNotify getDefaultInstance() {
      return defaultInstance;
    }

    public ChatRoomMessageNotify getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ChatRoomMessageNotify(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              ritemov2.commonModule.protobuf.BFBaseDefine.MsgType value = ritemov2.commonModule.protobuf.BFBaseDefine.MsgType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              steamid_ = input.readInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              msg_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ritemov2.commonModule.protobuf.BFIMMessage.internal_static_BF_IMMessage_ChatRoomMessageNotify_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ritemov2.commonModule.protobuf.BFIMMessage.internal_static_BF_IMMessage_ChatRoomMessageNotify_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ritemov2.commonModule.protobuf.BFIMMessage.ChatRoomMessageNotify.class, ritemov2.commonModule.protobuf.BFIMMessage.ChatRoomMessageNotify.Builder.class);
    }

    public static com.google.protobuf.Parser<ChatRoomMessageNotify> PARSER =
        new com.google.protobuf.AbstractParser<ChatRoomMessageNotify>() {
      public ChatRoomMessageNotify parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChatRoomMessageNotify(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<ChatRoomMessageNotify> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private ritemov2.commonModule.protobuf.BFBaseDefine.MsgType type_;
    /**
     * <code>required .BF.BaseDefine.MsgType type = 1;</code>
     *
     * <pre>
     *CHAT_ROOM_MESSAGE_NOTIFY
     * </pre>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .BF.BaseDefine.MsgType type = 1;</code>
     *
     * <pre>
     *CHAT_ROOM_MESSAGE_NOTIFY
     * </pre>
     */
    public ritemov2.commonModule.protobuf.BFBaseDefine.MsgType getType() {
      return type_;
    }

    public static final int STEAMID_FIELD_NUMBER = 2;
    private int steamid_;
    /**
     * <code>required int32 steamid = 2;</code>
     */
    public boolean hasSteamid() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 steamid = 2;</code>
     */
    public int getSteamid() {
      return steamid_;
    }

    public static final int MSG_FIELD_NUMBER = 3;
    private Object msg_;
    /**
     * <code>required string msg = 3;</code>
     */
    public boolean hasMsg() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string msg = 3;</code>
     */
    public String getMsg() {
      Object ref = msg_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string msg = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMsgBytes() {
      Object ref = msg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      type_ = ritemov2.commonModule.protobuf.BFBaseDefine.MsgType.MSG_SYSTEM;
      steamid_ = 0;
      msg_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSteamid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMsg()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, steamid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getMsgBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, steamid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getMsgBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ritemov2.commonModule.protobuf.BFIMMessage.ChatRoomMessageNotify parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ritemov2.commonModule.protobuf.BFIMMessage.ChatRoomMessageNotify parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ritemov2.commonModule.protobuf.BFIMMessage.ChatRoomMessageNotify parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ritemov2.commonModule.protobuf.BFIMMessage.ChatRoomMessageNotify parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ritemov2.commonModule.protobuf.BFIMMessage.ChatRoomMessageNotify parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ritemov2.commonModule.protobuf.BFIMMessage.ChatRoomMessageNotify parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ritemov2.commonModule.protobuf.BFIMMessage.ChatRoomMessageNotify parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ritemov2.commonModule.protobuf.BFIMMessage.ChatRoomMessageNotify parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ritemov2.commonModule.protobuf.BFIMMessage.ChatRoomMessageNotify parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ritemov2.commonModule.protobuf.BFIMMessage.ChatRoomMessageNotify parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ritemov2.commonModule.protobuf.BFIMMessage.ChatRoomMessageNotify prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BF.IMMessage.ChatRoomMessageNotify}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BF.IMMessage.ChatRoomMessageNotify)
        ritemov2.commonModule.protobuf.BFIMMessage.ChatRoomMessageNotifyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ritemov2.commonModule.protobuf.BFIMMessage.internal_static_BF_IMMessage_ChatRoomMessageNotify_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ritemov2.commonModule.protobuf.BFIMMessage.internal_static_BF_IMMessage_ChatRoomMessageNotify_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ritemov2.commonModule.protobuf.BFIMMessage.ChatRoomMessageNotify.class, ritemov2.commonModule.protobuf.BFIMMessage.ChatRoomMessageNotify.Builder.class);
      }

      // Construct using ritemov2.commonModule.protobuf.BFIMMessage.ChatRoomMessageNotify.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = ritemov2.commonModule.protobuf.BFBaseDefine.MsgType.MSG_SYSTEM;
        bitField0_ = (bitField0_ & ~0x00000001);
        steamid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        msg_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ritemov2.commonModule.protobuf.BFIMMessage.internal_static_BF_IMMessage_ChatRoomMessageNotify_descriptor;
      }

      public ritemov2.commonModule.protobuf.BFIMMessage.ChatRoomMessageNotify getDefaultInstanceForType() {
        return ritemov2.commonModule.protobuf.BFIMMessage.ChatRoomMessageNotify.getDefaultInstance();
      }

      public ritemov2.commonModule.protobuf.BFIMMessage.ChatRoomMessageNotify build() {
        ritemov2.commonModule.protobuf.BFIMMessage.ChatRoomMessageNotify result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ritemov2.commonModule.protobuf.BFIMMessage.ChatRoomMessageNotify buildPartial() {
        ritemov2.commonModule.protobuf.BFIMMessage.ChatRoomMessageNotify result = new ritemov2.commonModule.protobuf.BFIMMessage.ChatRoomMessageNotify(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.steamid_ = steamid_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.msg_ = msg_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ritemov2.commonModule.protobuf.BFIMMessage.ChatRoomMessageNotify) {
          return mergeFrom((ritemov2.commonModule.protobuf.BFIMMessage.ChatRoomMessageNotify)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ritemov2.commonModule.protobuf.BFIMMessage.ChatRoomMessageNotify other) {
        if (other == ritemov2.commonModule.protobuf.BFIMMessage.ChatRoomMessageNotify.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasSteamid()) {
          setSteamid(other.getSteamid());
        }
        if (other.hasMsg()) {
          bitField0_ |= 0x00000004;
          msg_ = other.msg_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (!hasSteamid()) {
          
          return false;
        }
        if (!hasMsg()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ritemov2.commonModule.protobuf.BFIMMessage.ChatRoomMessageNotify parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ritemov2.commonModule.protobuf.BFIMMessage.ChatRoomMessageNotify) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private ritemov2.commonModule.protobuf.BFBaseDefine.MsgType type_ = ritemov2.commonModule.protobuf.BFBaseDefine.MsgType.MSG_SYSTEM;
      /**
       * <code>required .BF.BaseDefine.MsgType type = 1;</code>
       *
       * <pre>
       *CHAT_ROOM_MESSAGE_NOTIFY
       * </pre>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .BF.BaseDefine.MsgType type = 1;</code>
       *
       * <pre>
       *CHAT_ROOM_MESSAGE_NOTIFY
       * </pre>
       */
      public ritemov2.commonModule.protobuf.BFBaseDefine.MsgType getType() {
        return type_;
      }
      /**
       * <code>required .BF.BaseDefine.MsgType type = 1;</code>
       *
       * <pre>
       *CHAT_ROOM_MESSAGE_NOTIFY
       * </pre>
       */
      public Builder setType(ritemov2.commonModule.protobuf.BFBaseDefine.MsgType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .BF.BaseDefine.MsgType type = 1;</code>
       *
       * <pre>
       *CHAT_ROOM_MESSAGE_NOTIFY
       * </pre>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = ritemov2.commonModule.protobuf.BFBaseDefine.MsgType.MSG_SYSTEM;
        onChanged();
        return this;
      }

      private int steamid_ ;
      /**
       * <code>required int32 steamid = 2;</code>
       */
      public boolean hasSteamid() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 steamid = 2;</code>
       */
      public int getSteamid() {
        return steamid_;
      }
      /**
       * <code>required int32 steamid = 2;</code>
       */
      public Builder setSteamid(int value) {
        bitField0_ |= 0x00000002;
        steamid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 steamid = 2;</code>
       */
      public Builder clearSteamid() {
        bitField0_ = (bitField0_ & ~0x00000002);
        steamid_ = 0;
        onChanged();
        return this;
      }

      private Object msg_ = "";
      /**
       * <code>required string msg = 3;</code>
       */
      public boolean hasMsg() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string msg = 3;</code>
       */
      public String getMsg() {
        Object ref = msg_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            msg_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string msg = 3;</code>
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string msg = 3;</code>
       */
      public Builder setMsg(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string msg = 3;</code>
       */
      public Builder clearMsg() {
        bitField0_ = (bitField0_ & ~0x00000004);
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      /**
       * <code>required string msg = 3;</code>
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        msg_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:BF.IMMessage.ChatRoomMessageNotify)
    }

    static {
      defaultInstance = new ChatRoomMessageNotify(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:BF.IMMessage.ChatRoomMessageNotify)
  }

  public interface PeerToPeerRecvOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BF.IMMessage.PeerToPeerRecv)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 sender = 1;</code>
     *
     * <pre>
     *CHAT_P2P_MESSAGE_NOTIFY
     * </pre>
     */
    boolean hasSender();
    /**
     * <code>required int32 sender = 1;</code>
     *
     * <pre>
     *CHAT_P2P_MESSAGE_NOTIFY
     * </pre>
     */
    int getSender();

    /**
     * <code>required string msg = 2;</code>
     */
    boolean hasMsg();
    /**
     * <code>required string msg = 2;</code>
     */
    String getMsg();
    /**
     * <code>required string msg = 2;</code>
     */
    com.google.protobuf.ByteString
        getMsgBytes();
  }
  /**
   * Protobuf type {@code BF.IMMessage.PeerToPeerRecv}
   */
  public static final class PeerToPeerRecv extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:BF.IMMessage.PeerToPeerRecv)
      PeerToPeerRecvOrBuilder {
    // Use PeerToPeerRecv.newBuilder() to construct.
    private PeerToPeerRecv(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PeerToPeerRecv(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PeerToPeerRecv defaultInstance;
    public static PeerToPeerRecv getDefaultInstance() {
      return defaultInstance;
    }

    public PeerToPeerRecv getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PeerToPeerRecv(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              sender_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              msg_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ritemov2.commonModule.protobuf.BFIMMessage.internal_static_BF_IMMessage_PeerToPeerRecv_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ritemov2.commonModule.protobuf.BFIMMessage.internal_static_BF_IMMessage_PeerToPeerRecv_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ritemov2.commonModule.protobuf.BFIMMessage.PeerToPeerRecv.class, ritemov2.commonModule.protobuf.BFIMMessage.PeerToPeerRecv.Builder.class);
    }

    public static com.google.protobuf.Parser<PeerToPeerRecv> PARSER =
        new com.google.protobuf.AbstractParser<PeerToPeerRecv>() {
      public PeerToPeerRecv parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PeerToPeerRecv(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<PeerToPeerRecv> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int SENDER_FIELD_NUMBER = 1;
    private int sender_;
    /**
     * <code>required int32 sender = 1;</code>
     *
     * <pre>
     *CHAT_P2P_MESSAGE_NOTIFY
     * </pre>
     */
    public boolean hasSender() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 sender = 1;</code>
     *
     * <pre>
     *CHAT_P2P_MESSAGE_NOTIFY
     * </pre>
     */
    public int getSender() {
      return sender_;
    }

    public static final int MSG_FIELD_NUMBER = 2;
    private Object msg_;
    /**
     * <code>required string msg = 2;</code>
     */
    public boolean hasMsg() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string msg = 2;</code>
     */
    public String getMsg() {
      Object ref = msg_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string msg = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMsgBytes() {
      Object ref = msg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      sender_ = 0;
      msg_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasSender()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMsg()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, sender_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getMsgBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, sender_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getMsgBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ritemov2.commonModule.protobuf.BFIMMessage.PeerToPeerRecv parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ritemov2.commonModule.protobuf.BFIMMessage.PeerToPeerRecv parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ritemov2.commonModule.protobuf.BFIMMessage.PeerToPeerRecv parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ritemov2.commonModule.protobuf.BFIMMessage.PeerToPeerRecv parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ritemov2.commonModule.protobuf.BFIMMessage.PeerToPeerRecv parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ritemov2.commonModule.protobuf.BFIMMessage.PeerToPeerRecv parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ritemov2.commonModule.protobuf.BFIMMessage.PeerToPeerRecv parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ritemov2.commonModule.protobuf.BFIMMessage.PeerToPeerRecv parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ritemov2.commonModule.protobuf.BFIMMessage.PeerToPeerRecv parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ritemov2.commonModule.protobuf.BFIMMessage.PeerToPeerRecv parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ritemov2.commonModule.protobuf.BFIMMessage.PeerToPeerRecv prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BF.IMMessage.PeerToPeerRecv}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BF.IMMessage.PeerToPeerRecv)
        ritemov2.commonModule.protobuf.BFIMMessage.PeerToPeerRecvOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ritemov2.commonModule.protobuf.BFIMMessage.internal_static_BF_IMMessage_PeerToPeerRecv_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ritemov2.commonModule.protobuf.BFIMMessage.internal_static_BF_IMMessage_PeerToPeerRecv_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ritemov2.commonModule.protobuf.BFIMMessage.PeerToPeerRecv.class, ritemov2.commonModule.protobuf.BFIMMessage.PeerToPeerRecv.Builder.class);
      }

      // Construct using ritemov2.commonModule.protobuf.BFIMMessage.PeerToPeerRecv.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        sender_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        msg_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ritemov2.commonModule.protobuf.BFIMMessage.internal_static_BF_IMMessage_PeerToPeerRecv_descriptor;
      }

      public ritemov2.commonModule.protobuf.BFIMMessage.PeerToPeerRecv getDefaultInstanceForType() {
        return ritemov2.commonModule.protobuf.BFIMMessage.PeerToPeerRecv.getDefaultInstance();
      }

      public ritemov2.commonModule.protobuf.BFIMMessage.PeerToPeerRecv build() {
        ritemov2.commonModule.protobuf.BFIMMessage.PeerToPeerRecv result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ritemov2.commonModule.protobuf.BFIMMessage.PeerToPeerRecv buildPartial() {
        ritemov2.commonModule.protobuf.BFIMMessage.PeerToPeerRecv result = new ritemov2.commonModule.protobuf.BFIMMessage.PeerToPeerRecv(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.sender_ = sender_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.msg_ = msg_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ritemov2.commonModule.protobuf.BFIMMessage.PeerToPeerRecv) {
          return mergeFrom((ritemov2.commonModule.protobuf.BFIMMessage.PeerToPeerRecv)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ritemov2.commonModule.protobuf.BFIMMessage.PeerToPeerRecv other) {
        if (other == ritemov2.commonModule.protobuf.BFIMMessage.PeerToPeerRecv.getDefaultInstance()) return this;
        if (other.hasSender()) {
          setSender(other.getSender());
        }
        if (other.hasMsg()) {
          bitField0_ |= 0x00000002;
          msg_ = other.msg_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSender()) {
          
          return false;
        }
        if (!hasMsg()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ritemov2.commonModule.protobuf.BFIMMessage.PeerToPeerRecv parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ritemov2.commonModule.protobuf.BFIMMessage.PeerToPeerRecv) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int sender_ ;
      /**
       * <code>required int32 sender = 1;</code>
       *
       * <pre>
       *CHAT_P2P_MESSAGE_NOTIFY
       * </pre>
       */
      public boolean hasSender() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 sender = 1;</code>
       *
       * <pre>
       *CHAT_P2P_MESSAGE_NOTIFY
       * </pre>
       */
      public int getSender() {
        return sender_;
      }
      /**
       * <code>required int32 sender = 1;</code>
       *
       * <pre>
       *CHAT_P2P_MESSAGE_NOTIFY
       * </pre>
       */
      public Builder setSender(int value) {
        bitField0_ |= 0x00000001;
        sender_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 sender = 1;</code>
       *
       * <pre>
       *CHAT_P2P_MESSAGE_NOTIFY
       * </pre>
       */
      public Builder clearSender() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sender_ = 0;
        onChanged();
        return this;
      }

      private Object msg_ = "";
      /**
       * <code>required string msg = 2;</code>
       */
      public boolean hasMsg() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string msg = 2;</code>
       */
      public String getMsg() {
        Object ref = msg_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            msg_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string msg = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string msg = 2;</code>
       */
      public Builder setMsg(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string msg = 2;</code>
       */
      public Builder clearMsg() {
        bitField0_ = (bitField0_ & ~0x00000002);
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      /**
       * <code>required string msg = 2;</code>
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        msg_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:BF.IMMessage.PeerToPeerRecv)
    }

    static {
      defaultInstance = new PeerToPeerRecv(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:BF.IMMessage.PeerToPeerRecv)
  }

  public interface PeerToPeerSendOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BF.IMMessage.PeerToPeerSend)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 sender = 1;</code>
     *
     * <pre>
     *CHAT_SEND_P2P_MESSAGE
     * </pre>
     */
    boolean hasSender();
    /**
     * <code>required int32 sender = 1;</code>
     *
     * <pre>
     *CHAT_SEND_P2P_MESSAGE
     * </pre>
     */
    int getSender();

    /**
     * <code>required int32 recver = 2;</code>
     *
     * <pre>
     *steamid
     * </pre>
     */
    boolean hasRecver();
    /**
     * <code>required int32 recver = 2;</code>
     *
     * <pre>
     *steamid
     * </pre>
     */
    int getRecver();

    /**
     * <code>required string msg = 3;</code>
     */
    boolean hasMsg();
    /**
     * <code>required string msg = 3;</code>
     */
    String getMsg();
    /**
     * <code>required string msg = 3;</code>
     */
    com.google.protobuf.ByteString
        getMsgBytes();
  }
  /**
   * Protobuf type {@code BF.IMMessage.PeerToPeerSend}
   */
  public static final class PeerToPeerSend extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:BF.IMMessage.PeerToPeerSend)
      PeerToPeerSendOrBuilder {
    // Use PeerToPeerSend.newBuilder() to construct.
    private PeerToPeerSend(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PeerToPeerSend(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PeerToPeerSend defaultInstance;
    public static PeerToPeerSend getDefaultInstance() {
      return defaultInstance;
    }

    public PeerToPeerSend getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PeerToPeerSend(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              sender_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              recver_ = input.readInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              msg_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ritemov2.commonModule.protobuf.BFIMMessage.internal_static_BF_IMMessage_PeerToPeerSend_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ritemov2.commonModule.protobuf.BFIMMessage.internal_static_BF_IMMessage_PeerToPeerSend_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ritemov2.commonModule.protobuf.BFIMMessage.PeerToPeerSend.class, ritemov2.commonModule.protobuf.BFIMMessage.PeerToPeerSend.Builder.class);
    }

    public static com.google.protobuf.Parser<PeerToPeerSend> PARSER =
        new com.google.protobuf.AbstractParser<PeerToPeerSend>() {
      public PeerToPeerSend parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PeerToPeerSend(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<PeerToPeerSend> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int SENDER_FIELD_NUMBER = 1;
    private int sender_;
    /**
     * <code>required int32 sender = 1;</code>
     *
     * <pre>
     *CHAT_SEND_P2P_MESSAGE
     * </pre>
     */
    public boolean hasSender() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 sender = 1;</code>
     *
     * <pre>
     *CHAT_SEND_P2P_MESSAGE
     * </pre>
     */
    public int getSender() {
      return sender_;
    }

    public static final int RECVER_FIELD_NUMBER = 2;
    private int recver_;
    /**
     * <code>required int32 recver = 2;</code>
     *
     * <pre>
     *steamid
     * </pre>
     */
    public boolean hasRecver() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 recver = 2;</code>
     *
     * <pre>
     *steamid
     * </pre>
     */
    public int getRecver() {
      return recver_;
    }

    public static final int MSG_FIELD_NUMBER = 3;
    private Object msg_;
    /**
     * <code>required string msg = 3;</code>
     */
    public boolean hasMsg() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string msg = 3;</code>
     */
    public String getMsg() {
      Object ref = msg_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string msg = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMsgBytes() {
      Object ref = msg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      sender_ = 0;
      recver_ = 0;
      msg_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasSender()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRecver()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMsg()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, sender_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, recver_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getMsgBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, sender_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, recver_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getMsgBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ritemov2.commonModule.protobuf.BFIMMessage.PeerToPeerSend parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ritemov2.commonModule.protobuf.BFIMMessage.PeerToPeerSend parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ritemov2.commonModule.protobuf.BFIMMessage.PeerToPeerSend parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ritemov2.commonModule.protobuf.BFIMMessage.PeerToPeerSend parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ritemov2.commonModule.protobuf.BFIMMessage.PeerToPeerSend parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ritemov2.commonModule.protobuf.BFIMMessage.PeerToPeerSend parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ritemov2.commonModule.protobuf.BFIMMessage.PeerToPeerSend parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ritemov2.commonModule.protobuf.BFIMMessage.PeerToPeerSend parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ritemov2.commonModule.protobuf.BFIMMessage.PeerToPeerSend parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ritemov2.commonModule.protobuf.BFIMMessage.PeerToPeerSend parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ritemov2.commonModule.protobuf.BFIMMessage.PeerToPeerSend prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BF.IMMessage.PeerToPeerSend}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BF.IMMessage.PeerToPeerSend)
        ritemov2.commonModule.protobuf.BFIMMessage.PeerToPeerSendOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ritemov2.commonModule.protobuf.BFIMMessage.internal_static_BF_IMMessage_PeerToPeerSend_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ritemov2.commonModule.protobuf.BFIMMessage.internal_static_BF_IMMessage_PeerToPeerSend_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ritemov2.commonModule.protobuf.BFIMMessage.PeerToPeerSend.class, ritemov2.commonModule.protobuf.BFIMMessage.PeerToPeerSend.Builder.class);
      }

      // Construct using ritemov2.commonModule.protobuf.BFIMMessage.PeerToPeerSend.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        sender_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        recver_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        msg_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ritemov2.commonModule.protobuf.BFIMMessage.internal_static_BF_IMMessage_PeerToPeerSend_descriptor;
      }

      public ritemov2.commonModule.protobuf.BFIMMessage.PeerToPeerSend getDefaultInstanceForType() {
        return ritemov2.commonModule.protobuf.BFIMMessage.PeerToPeerSend.getDefaultInstance();
      }

      public ritemov2.commonModule.protobuf.BFIMMessage.PeerToPeerSend build() {
        ritemov2.commonModule.protobuf.BFIMMessage.PeerToPeerSend result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ritemov2.commonModule.protobuf.BFIMMessage.PeerToPeerSend buildPartial() {
        ritemov2.commonModule.protobuf.BFIMMessage.PeerToPeerSend result = new ritemov2.commonModule.protobuf.BFIMMessage.PeerToPeerSend(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.sender_ = sender_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.recver_ = recver_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.msg_ = msg_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ritemov2.commonModule.protobuf.BFIMMessage.PeerToPeerSend) {
          return mergeFrom((ritemov2.commonModule.protobuf.BFIMMessage.PeerToPeerSend)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ritemov2.commonModule.protobuf.BFIMMessage.PeerToPeerSend other) {
        if (other == ritemov2.commonModule.protobuf.BFIMMessage.PeerToPeerSend.getDefaultInstance()) return this;
        if (other.hasSender()) {
          setSender(other.getSender());
        }
        if (other.hasRecver()) {
          setRecver(other.getRecver());
        }
        if (other.hasMsg()) {
          bitField0_ |= 0x00000004;
          msg_ = other.msg_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSender()) {
          
          return false;
        }
        if (!hasRecver()) {
          
          return false;
        }
        if (!hasMsg()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ritemov2.commonModule.protobuf.BFIMMessage.PeerToPeerSend parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ritemov2.commonModule.protobuf.BFIMMessage.PeerToPeerSend) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int sender_ ;
      /**
       * <code>required int32 sender = 1;</code>
       *
       * <pre>
       *CHAT_SEND_P2P_MESSAGE
       * </pre>
       */
      public boolean hasSender() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 sender = 1;</code>
       *
       * <pre>
       *CHAT_SEND_P2P_MESSAGE
       * </pre>
       */
      public int getSender() {
        return sender_;
      }
      /**
       * <code>required int32 sender = 1;</code>
       *
       * <pre>
       *CHAT_SEND_P2P_MESSAGE
       * </pre>
       */
      public Builder setSender(int value) {
        bitField0_ |= 0x00000001;
        sender_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 sender = 1;</code>
       *
       * <pre>
       *CHAT_SEND_P2P_MESSAGE
       * </pre>
       */
      public Builder clearSender() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sender_ = 0;
        onChanged();
        return this;
      }

      private int recver_ ;
      /**
       * <code>required int32 recver = 2;</code>
       *
       * <pre>
       *steamid
       * </pre>
       */
      public boolean hasRecver() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 recver = 2;</code>
       *
       * <pre>
       *steamid
       * </pre>
       */
      public int getRecver() {
        return recver_;
      }
      /**
       * <code>required int32 recver = 2;</code>
       *
       * <pre>
       *steamid
       * </pre>
       */
      public Builder setRecver(int value) {
        bitField0_ |= 0x00000002;
        recver_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 recver = 2;</code>
       *
       * <pre>
       *steamid
       * </pre>
       */
      public Builder clearRecver() {
        bitField0_ = (bitField0_ & ~0x00000002);
        recver_ = 0;
        onChanged();
        return this;
      }

      private Object msg_ = "";
      /**
       * <code>required string msg = 3;</code>
       */
      public boolean hasMsg() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string msg = 3;</code>
       */
      public String getMsg() {
        Object ref = msg_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            msg_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string msg = 3;</code>
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string msg = 3;</code>
       */
      public Builder setMsg(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string msg = 3;</code>
       */
      public Builder clearMsg() {
        bitField0_ = (bitField0_ & ~0x00000004);
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      /**
       * <code>required string msg = 3;</code>
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        msg_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:BF.IMMessage.PeerToPeerSend)
    }

    static {
      defaultInstance = new PeerToPeerSend(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:BF.IMMessage.PeerToPeerSend)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BF_IMMessage_ChatSendRoomMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BF_IMMessage_ChatSendRoomMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BF_IMMessage_ChatRoomMessageNotify_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BF_IMMessage_ChatRoomMessageNotify_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BF_IMMessage_PeerToPeerRecv_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BF_IMMessage_PeerToPeerRecv_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BF_IMMessage_PeerToPeerSend_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BF_IMMessage_PeerToPeerSend_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\022BF.IMMessage.proto\022\014BF.IMMessage\032\023BF.B" +
      "aseDefine.proto\"k\n\023ChatSendRoomMessage\022$" +
      "\n\004type\030\001 \002(\0162\026.BF.BaseDefine.MsgType\022\017\n\007" +
      "steamid\030\002 \002(\005\022\020\n\010gameroom\030\003 \002(\t\022\013\n\003msg\030\004" +
      " \002(\t\"[\n\025ChatRoomMessageNotify\022$\n\004type\030\001 " +
      "\002(\0162\026.BF.BaseDefine.MsgType\022\017\n\007steamid\030\002" +
      " \002(\005\022\013\n\003msg\030\003 \002(\t\"-\n\016PeerToPeerRecv\022\016\n\006s" +
      "ender\030\001 \002(\005\022\013\n\003msg\030\002 \002(\t\"=\n\016PeerToPeerSe" +
      "nd\022\016\n\006sender\030\001 \002(\005\022\016\n\006recver\030\002 \002(\005\022\013\n\003ms" +
      "g\030\003 \002(\tB!\n\037com.benq.csgov2.common.protob",
      "uf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ritemov2.commonModule.protobuf.BFBaseDefine.getDescriptor(),
        }, assigner);
    internal_static_BF_IMMessage_ChatSendRoomMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_BF_IMMessage_ChatSendRoomMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_BF_IMMessage_ChatSendRoomMessage_descriptor,
        new String[] { "Type", "Steamid", "Gameroom", "Msg", });
    internal_static_BF_IMMessage_ChatRoomMessageNotify_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_BF_IMMessage_ChatRoomMessageNotify_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_BF_IMMessage_ChatRoomMessageNotify_descriptor,
        new String[] { "Type", "Steamid", "Msg", });
    internal_static_BF_IMMessage_PeerToPeerRecv_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_BF_IMMessage_PeerToPeerRecv_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_BF_IMMessage_PeerToPeerRecv_descriptor,
        new String[] { "Sender", "Msg", });
    internal_static_BF_IMMessage_PeerToPeerSend_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_BF_IMMessage_PeerToPeerSend_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_BF_IMMessage_PeerToPeerSend_descriptor,
        new String[] { "Sender", "Recver", "Msg", });
    ritemov2.commonModule.protobuf.BFBaseDefine.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
